const SYNC_URL="https://ebmcckbjugbivfqimnux.supabase.co/functions/v1/quick-service";
const SAMPLE={settings:{pin:"",richardColor:"#4776c8",timothyColor:"#d77955",city1:"Las Vegas",city2:"Flagstaff"},events:[{id:1,title:"Soccer Practice",person:"Richard",type:"Practice",date:nextDow(2),time:"17:30",end:"19:00",location:"Desert Sports Complex",leave:"16:55",bring:"Cleats, water bottle"},{id:2,title:"Math Homework Due",person:"Timothy",type:"Homework",date:nextDow(3),time:"08:00",location:"School"},{id:3,title:"Kids to Dad",person:"Both",type:"Custody",date:nextDow(5),time:"17:30",recurring:"weekly"},{id:4,title:"Kids Return",person:"Both",type:"Custody",date:nextDow(0),time:"15:30",recurring:"weekly"},{id:5,title:"Pediatric Dentist",person:"Richard",type:"Appointment",date:addDays(5),time:"15:15",location:"Summerlin"}],payments:[{id:1,name:"Internet",day:18,amount:"75",paid:false},{id:2,name:"Car Insurance",day:21,amount:"",paid:false},{id:3,name:"Streaming",day:26,amount:"",paid:false}],staples:["Milk","Eggs","Bread","Bananas","Apples","Yogurt","Cereal","Chicken","Rice","Juice","Paper towels","Toilet paper","Laundry detergent"].map((name,i)=>({id:i+1,name,qty:1,need:i<5})),meals:[{id:1,name:"Tacos",ingredients:"Ground beef, tortillas, shredded cheese, lettuce, taco seasoning",recipe:"Brown beef, season, warm tortillas, assemble."},{id:2,name:"Chicken Alfredo",ingredients:"Chicken, pasta, Alfredo sauce, broccoli",recipe:"Cook pasta and chicken; combine with sauce and broccoli."},{id:3,name:"Spaghetti",ingredients:"Pasta, marinara, ground beef, parmesan",recipe:"Cook pasta; brown beef; simmer with marinara."},{id:4,name:"Burgers",ingredients:"Burger patties, buns, cheese, lettuce, tomato",recipe:"Grill patties and assemble."},{id:5,name:"Chicken & Rice",ingredients:"Chicken, rice, vegetables, seasoning",recipe:"Cook seasoned chicken; serve over rice with vegetables."}],mealPlan:{},tasks:[{id:1,name:"Take trash out",due:nextDow(3),done:false,repeat:"Weekly"},{id:2,name:"Change HVAC filter",due:addDays(6),done:false,repeat:"Monthly"},{id:3,name:"Wash sports uniforms",due:nextDow(5),done:false,repeat:"Weekly"}]};
function iso(d){return d.toISOString().slice(0,10)} function addDays(n){let d=new Date();d.setDate(d.getDate()+n);return iso(d)} function nextDow(x){let d=new Date(),n=(x-d.getDay()+7)%7;n=n||7;d.setDate(d.getDate()+n);return iso(d)}
let data=JSON.parse(localStorage.getItem('familyHubData')||'null')||SAMPLE; let view='home'; let activePin=sessionStorage.getItem('familyHubPin')||localStorage.getItem('familyHubPin')||'';
const $=s=>document.querySelector(s);
function localSave(){localStorage.setItem('familyHubData',JSON.stringify(data))}
async function syncLoad(pin){const r=await fetch(SYNC_URL,{headers:{'x-family-pin':pin}});if(!r.ok)throw new Error(r.status===401?'Invalid PIN':'Sync unavailable');const j=await r.json();if(j.data&&Object.keys(j.data).length){data=j.data;localSave()}else{await syncSave(pin)}return data}
async function syncSave(pin=activePin){localSave();if(!pin)return;try{const r=await fetch(SYNC_URL,{method:'POST',headers:{'Content-Type':'application/json','x-family-pin':pin},body:JSON.stringify({data})});if(!r.ok)throw new Error('Sync failed')}catch(e){console.warn('Family Hub sync:',e)}}
const save=()=>syncSave();
async function unlock(){const pin=$('#pinInput').value;$('#pinMsg').textContent='Connecting…';try{await syncLoad(pin);activePin=pin;sessionStorage.setItem('familyHubPin',pin);if($('#rememberPin').checked){localStorage.setItem('familyHubUnlocked','1');localStorage.setItem('familyHubPin',pin)}$('#pinGate').classList.add('hidden');$('#app').classList.remove('hidden');$('#pinMsg').textContent='';render()}catch(e){$('#pinMsg').textContent=e.message==='Invalid PIN'?'That PIN did not match.':'Could not connect. Check your internet and try again.'}} $('#unlockBtn').onclick=unlock; $('#pinInput').onkeydown=e=>{if(e.key==='Enter')unlock()}; if(localStorage.getItem('familyHubUnlocked')&&activePin){syncLoad(activePin).then(()=>{$('#pinGate').classList.add('hidden');$('#app').classList.remove('hidden');render()}).catch(()=>{localStorage.removeItem('familyHubUnlocked');localStorage.removeItem('familyHubPin')})}
function personColor(p){return p==='Richard'?data.settings.richardColor:p==='Timothy'?data.settings.timothyColor:'#8b7b67'} function fmtDate(s){return new Date(s+'T12:00').toLocaleDateString([], {weekday:'short',month:'short',day:'numeric'})}
async function weather(){let places=[['Las Vegas',36.1716,-115.1391],['Flagstaff',35.1983,-111.6513]];for(let [name,lat,lon] of places){try{let r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,weather_code&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&temperature_unit=fahrenheit&forecast_days=7&timezone=auto`),j=await r.json();let el=document.querySelector(`[data-weather="${name}"]`);if(el)el.innerHTML=`<b>${name}</b><div class="temp">${Math.round(j.current.temperature_2m)}°</div><div class="meta">H ${Math.round(j.daily.temperature_2m_max[0])}° · L ${Math.round(j.daily.temperature_2m_min[0])}° · ${j.daily.precipitation_probability_max[0]}% rain</div>`}catch{}}}
function render(){let now=new Date();$('#todayLabel').textContent=now.toLocaleDateString([],{weekday:'long',month:'long',day:'numeric'});let upcoming=data.events.filter(e=>e.date>=iso(now)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));let need=data.staples.filter(x=>x.need).length;$('#summary').textContent=`${upcoming.filter(e=>e.date===iso(now)).length} events today · ${data.payments.filter(p=>!p.paid).length} payments upcoming · ${need} groceries needed`; let root=$('#dashboard');root.innerHTML=view==='home'?home():view==='calendar'?calendarView():view==='shop'?shopView():view==='meals'?mealsView():moreView();weather();bind()}
function home(){let ev=data.events.filter(e=>e.date>=iso(new Date())).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).slice(0,6);return `<section class="card wide"><div class="card-head"><h2>Coming up</h2><span class="pill">Next 7 days</span></div>${ev.map(eventRow).join('')}</section><section class="card"><h2>Weather</h2><div class="weather-row"><div class="weather" data-weather="Las Vegas">Loading…</div><div class="weather" data-weather="Flagstaff">Loading…</div></div></section><section class="card full"><div class="card-head"><h2>Week at a glance</h2><button data-go="calendar">Open calendar</button></div>${weekStrip()}</section><section class="card"><div class="card-head"><h2>Shopping</h2><span class="pill">${data.staples.filter(x=>x.need).length} needed</span></div>${data.staples.filter(x=>x.need).slice(0,5).map(x=>`<div class="item">☐ <div>${x.name}${x.qty>1?` ×${x.qty}`:''}</div></div>`).join('')}<div class="actions"><button data-go="shop">Review staples</button></div></section><section class="card"><h2>Meals this week</h2>${mealPlanRows()}<div class="actions"><button data-go="meals">Plan week</button></div></section><section class="card"><h2>Payments</h2>${data.payments.filter(p=>!p.paid).slice(0,4).map(p=>`<div class="item"><div><b>${p.name}</b><div class="meta">Due ${p.day}${p.amount?` · $${p.amount}`:''}</div></div></div>`).join('')}</section><section class="card"><h2>Household</h2>${data.tasks.slice(0,4).map(t=>`<div class="item"><input class="check task-check" data-id="${t.id}" type="checkbox" ${t.done?'checked':''}><div>${t.name}<div class="meta">${fmtDate(t.due)} · ${t.repeat}</div></div></div>`).join('')}</section>`}
function eventRow(e){return `<div class="item"><span class="dot" style="background:${personColor(e.person)}"></span><div><b>${e.title}</b><div class="meta">${fmtDate(e.date)} · ${e.time}${e.location?` · ${e.location}`:''}${e.leave?` · Leave ${e.leave}`:''}</div><div class="meta">${e.person} · ${e.type}</div></div></div>`}
function weekStrip(){return `<div class="week">${[0,1,2,3,4,5,6].map(n=>{let d=addDays(n),dt=new Date(d+'T12:00'),es=data.events.filter(e=>e.date===d);return `<div class="day"><b>${dt.toLocaleDateString([],{weekday:'short'})}<br>${dt.getDate()}</b>${es.map(e=>`<span class="tag" style="background:${personColor(e.person)}">${e.title}</span>`).join('')}</div>`}).join('')}</div>`}
function calendarView(){return `<section class="card full"><div class="card-head"><h2>Family calendar</h2><button id="addEvent">＋ Event</button></div>${weekStrip()}<div style="margin-top:16px">${data.events.sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(eventRow).join('')}</div></section>`}
function shopView(){return `<section class="card wide"><div class="card-head"><h2>Weekly staples</h2><span class="pill">Resets Sunday</span></div>${data.staples.map(x=>`<div class="item"><input class="check staple-check" data-id="${x.id}" type="checkbox" ${x.need?'checked':''}><div style="flex:1"><b>${x.name}</b><div class="meta">${x.need?'Need':'Have it'}</div></div><input class="qty" data-id="${x.id}" type="number" min="1" value="${x.qty}" style="width:55px"></div>`).join('')}<div class="actions"><button id="addStaple">＋ Staple</button><button id="copyList" class="primary">Copy shopping list</button></div></section><section class="card"><h2>Ready for Instacart</h2>${data.staples.filter(x=>x.need).map(x=>`<div class="item">${x.name}${x.qty>1?` ×${x.qty}`:''}</div>`).join('')||'<p class="muted">Nothing needed yet.</p>'}</section>`}
function mealPlanRows(){return [0,1,2,3,4,5,6].map(n=>{let d=addDays(n),day=new Date(d+'T12:00').toLocaleDateString([],{weekday:'short'});return `<div class="meal"><b>${day}</b> · ${data.mealPlan[d]||'Not planned'}</div>`}).join('')}
function mealsView(){return `<section class="card wide"><h2>Plan the week</h2>${[0,1,2,3,4,5,6].map(n=>{let d=addDays(n),day=new Date(d+'T12:00').toLocaleDateString([],{weekday:'long'});return `<div class="item"><div style="width:90px"><b>${day}</b></div><select class="meal-select" data-date="${d}" style="flex:1;padding:8px;border-radius:9px;background:var(--bg);color:var(--text);border:1px solid var(--line)"><option value="">Not planned</option>${data.meals.map(m=>`<option ${data.mealPlan[d]===m.name?'selected':''}>${m.name}</option>`).join('')}</select></div>`}).join('')}</section><section class="card"><div class="card-head"><h2>Meal library</h2><button id="addMeal">＋</button></div>${data.meals.map(m=>`<div class="meal"><b>${m.name}</b><div class="meta">${m.ingredients}</div></div>`).join('')}</section>`}
function moreView(){return `<section class="card"><h2>Kids</h2><div class="item"><span class="dot" style="background:${data.settings.richardColor}"></span><b>Richard</b><input class="color" data-person="Richard" type="color" value="${data.settings.richardColor}" style="margin-left:auto"></div><div class="item"><span class="dot" style="background:${data.settings.timothyColor}"></span><b>Timothy</b><input class="color" data-person="Timothy" type="color" value="${data.settings.timothyColor}" style="margin-left:auto"></div></section><section class="card"><h2>Custody schedule</h2><p>Friday 5:30 PM — kids go with Dad</p><p>Sunday 3:30 PM — kids return</p><p class="meta">Add a one-off custody event to override a specific day.</p><button id="custodyOverride">Adjust a day</button></section><section class="card"><h2>Sync</h2><p class="meta">This starter runs locally immediately. Follow SETUP.md to enable Supabase sync with the included secure Edge Function.</p><button id="lock">Lock this device</button></section>`}
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{view=b.dataset.go;render()});document.querySelectorAll('.task-check').forEach(x=>x.onchange=()=>{data.tasks.find(t=>t.id==x.dataset.id).done=x.checked;save();render()});document.querySelectorAll('.staple-check').forEach(x=>x.onchange=()=>{data.staples.find(t=>t.id==x.dataset.id).need=x.checked;save();render()});document.querySelectorAll('.qty').forEach(x=>x.onchange=()=>{data.staples.find(t=>t.id==x.dataset.id).qty=+x.value||1;save()});document.querySelectorAll('.meal-select').forEach(x=>x.onchange=()=>{data.mealPlan[x.dataset.date]=x.value;save();render()});document.querySelectorAll('.color').forEach(x=>x.onchange=()=>{data.settings[x.dataset.person.toLowerCase()+'Color']=x.value;save();render()});$('#addEvent')&&($('#addEvent').onclick=eventForm);$('#custodyOverride')&&($('#custodyOverride').onclick=eventForm);$('#addStaple')&&($('#addStaple').onclick=()=>simplePrompt('Add staple','Staple name',v=>{data.staples.push({id:Date.now(),name:v,qty:1,need:true});save();render()}));$('#addMeal')&&($('#addMeal').onclick=()=>simplePrompt('Add meal','Meal name',v=>{data.meals.push({id:Date.now(),name:v,ingredients:'',recipe:''});save();render()}));$('#copyList')&&($('#copyList').onclick=async()=>{let s=data.staples.filter(x=>x.need).map(x=>`${x.name}${x.qty>1?` x${x.qty}`:''}`).join('\n');await navigator.clipboard.writeText(s);alert('Shopping list copied.');});$('#lock')&&($('#lock').onclick=()=>{localStorage.removeItem('familyHubUnlocked');localStorage.removeItem('familyHubPin');sessionStorage.removeItem('familyHubPin');location.reload()})}
function simplePrompt(title,label,cb){let v=prompt(`${title}\n${label}:`);if(v&&v.trim())cb(v.trim())}
function eventForm(){let title=prompt('Event name');if(!title)return;let person=prompt('Who? Richard, Timothy, Both','Both')||'Both',date=prompt('Date (YYYY-MM-DD)',addDays(1))||addDays(1),time=prompt('Time (HH:MM)','17:30')||'17:30',type=prompt('Type: Practice, Game, School, Appointment, Custody, Homework','School')||'Other';data.events.push({id:Date.now(),title,person,type,date,time});save();render()}
$('#quickAdd').onclick=eventForm;document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});$('#editDashboard').onclick=()=>{view='more';render()};
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js');


/* ===== Family Hub V1.1 ===== */
let calCursor=new Date(); calCursor.setDate(1);
function normalizeV11(){
  data.staples=(data.staples||[]).filter(x=>String(x.name).trim().toUpperCase()!=='SYNC TEST');
  data.settings=data.settings||{};
  data.settings.custodyOverrides=data.settings.custodyOverrides||{};
  data.payments=data.payments||[]; data.tasks=data.tasks||[]; data.meals=data.meals||[]; data.events=data.events||[];
}
const _syncLoadV10=syncLoad;
syncLoad=async function(pin){let r=await _syncLoadV10(pin);normalizeV11();await syncSave(pin);return r}
function custodyForDate(date){
  normalizeV11();
  if(data.settings.custodyOverrides[date])return data.settings.custodyOverrides[date];
  const dow=new Date(date+'T12:00').getDay();
  if(dow===5)return 'Dad after 5:30';
  if(dow===6)return 'Dad';
  if(dow===0)return 'Dad → Mom 3:30';
  return 'Mom';
}
function custodyColor(label){return label.includes('Dad')&&!label.includes('Mom')?'#6f7f9d':label.includes('→')?'#9b7fa5':'#8aa786'}
function eventRow(e){return `<div class="item"><span class="dot" style="background:${personColor(e.person)}"></span><div style="flex:1"><b>${e.title}</b><div class="meta">${fmtDate(e.date)} · ${e.time||''}${e.location?` · ${e.location}`:''}${e.leave?` · Leave ${e.leave}`:''}</div><div class="meta">${e.person} · ${e.type}</div></div><div class="item-actions"><button class="mini edit-event" data-id="${e.id}">Edit</button><button class="mini danger delete-event" data-id="${e.id}">Delete</button></div></div>`}
function calendarView(){
  const y=calCursor.getFullYear(),m=calCursor.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-first.getDay());
  let days=''; for(let i=0;i<42;i++){let d=new Date(start);d.setDate(start.getDate()+i);let ds=iso(d),other=d.getMonth()!==m,ev=data.events.filter(e=>e.date===ds),cust=custodyForDate(ds);days+=`<div class="cal-day ${other?'other':''}"><div class="cal-num">${d.getDate()}</div><button class="cal-custody custody-toggle" data-date="${ds}" title="Tap to toggle custody" style="width:100%;background:${custodyColor(cust)};padding:0"></button><div class="meta" style="font-size:9px">${cust}</div>${ev.slice(0,3).map(e=>`<div class="cal-event edit-event" data-id="${e.id}" style="background:${personColor(e.person)}">${e.title}</div>`).join('')}</div>`}
  return `<section class="card full"><div class="card-head"><div><h2>Family calendar</h2><div class="meta">Custody colors: green = Mom · blue = Dad · purple = transition</div></div><div class="actions"><button id="prevMonth">‹</button><b>${calCursor.toLocaleDateString([],{month:'long',year:'numeric'})}</b><button id="nextMonth">›</button><button id="addEvent">＋ Event</button></div></div><div class="calendar-grid">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div class="cal-head">${x}</div>`).join('')}${days}</div><div style="margin-top:18px"><h2>List view</h2>${data.events.slice().sort((a,b)=>(a.date+(a.time||'')).localeCompare(b.date+(b.time||''))).map(eventRow).join('')}</div></section>`}
}
function shopView(){return `<section class="card wide"><div class="card-head"><h2>Weekly staples</h2><span class="pill">Review Sundays</span></div>${data.staples.map(x=>`<div class="item"><input class="check staple-check" data-id="${x.id}" type="checkbox" ${x.need?'checked':''}><div style="flex:1"><b>${x.name}</b><div class="meta">${x.need?'Need':'Have it'}</div></div><input class="qty" data-id="${x.id}" type="number" min="1" value="${x.qty}" style="width:55px"><div class="item-actions"><button class="mini edit-staple" data-id="${x.id}">Edit</button><button class="mini danger delete-staple" data-id="${x.id}">Delete</button></div></div>`).join('')}<div class="actions"><button id="addStaple">＋ Staple</button><button id="copyList" class="primary">Copy shopping list</button></div></section><section class="card"><h2>Ready for Instacart</h2>${data.staples.filter(x=>x.need).map(x=>`<div class="item">${x.name}${x.qty>1?` ×${x.qty}`:''}</div>`).join('')||'<p class="muted">Nothing needed yet.</p>'}</section>`}
}
function mealsView(){return `<section class="card wide"><h2>Plan the week</h2>${[0,1,2,3,4,5,6].map(n=>{let d=addDays(n),day=new Date(d+'T12:00').toLocaleDateString([],{weekday:'long'});return `<div class="item"><div style="width:90px"><b>${day}</b></div><select class="meal-select" data-date="${d}" style="flex:1;padding:8px;border-radius:9px;background:var(--bg);color:var(--text);border:1px solid var(--line)"><option value="">Not planned</option>${data.meals.map(m=>`<option ${data.mealPlan[d]===m.name?'selected':''}>${m.name}</option>`).join('')}</select></div>`}).join('')}</section><section class="card"><div class="card-head"><h2>Meal library</h2><button id="addMeal">＋ Meal</button></div>${data.meals.map(m=>`<div class="meal"><div class="card-head"><b>${m.name}</b><div><button class="mini edit-meal" data-id="${m.id}">Edit</button> <button class="mini danger delete-meal" data-id="${m.id}">Delete</button></div></div><div class="meta">${m.ingredients||'No ingredients yet'}</div></div>`).join('')}</section>`}
}
function moreView(){return `<section class="card"><h2>Kids</h2><div class="item"><span class="dot" style="background:${data.settings.richardColor}"></span><b>Richard</b><input class="color" data-person="Richard" type="color" value="${data.settings.richardColor}" style="margin-left:auto"></div><div class="item"><span class="dot" style="background:${data.settings.timothyColor}"></span><b>Timothy</b><input class="color" data-person="Timothy" type="color" value="${data.settings.timothyColor}" style="margin-left:auto"></div></section><section class="card"><div class="card-head"><h2>Payments</h2><button id="addPayment">＋</button></div>${data.payments.map(p=>`<div class="item"><input class="check payment-check" data-id="${p.id}" type="checkbox" ${p.paid?'checked':''}><div style="flex:1"><b>${p.name}</b><div class="meta">Due ${p.day}${p.amount?` · $${p.amount}`:''}</div></div><button class="mini edit-payment" data-id="${p.id}">Edit</button><button class="mini danger delete-payment" data-id="${p.id}">Delete</button></div>`).join('')}</section><section class="card"><div class="card-head"><h2>Household & school</h2><button id="addTask">＋</button></div>${data.tasks.map(t=>`<div class="item"><input class="check task-check" data-id="${t.id}" type="checkbox" ${t.done?'checked':''}><div style="flex:1">${t.name}<div class="meta">${fmtDate(t.due)} · ${t.repeat}</div></div><button class="mini edit-task" data-id="${t.id}">Edit</button><button class="mini danger delete-task" data-id="${t.id}">Delete</button></div>`).join('')}</section><section class="card"><h2>Custody</h2><p>Friday 5:30 PM → Dad</p><p>Sunday 3:30 PM → Mom</p><p class="meta">Tap the custody marker on any calendar day for a one-day override.</p></section><section class="card"><h2>Sync</h2><p class="meta">Cloud sync is active across your Family Hub devices.</p><button id="lock">Lock this device</button></section>`}
}
function openEventEditor(id){
  const e=id?data.events.find(x=>x.id==id):{id:Date.now(),title:'',person:'Both',type:'School',date:addDays(1),time:'17:30',end:'',location:'',leave:'',bring:'',notes:''};
  const isNew=!id; $('#modalTitle').textContent=isNew?'Add event':'Edit event'; $('#modalBody').innerHTML=`<div class="form-grid"><label class="field full">Title<input id="evTitle" value="${e.title||''}"></label><label class="field">Person<select id="evPerson">${['Richard','Timothy','Both'].map(x=>`<option ${e.person===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="field">Type<select id="evType">${['Practice','Game','School','Appointment','Custody','Homework','Other'].map(x=>`<option ${e.type===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="field">Date<input id="evDate" type="date" value="${e.date}"></label><label class="field">Start<input id="evTime" type="time" value="${e.time||''}"></label><label class="field">End<input id="evEnd" type="time" value="${e.end||''}"></label><label class="field">Leave by<input id="evLeave" type="time" value="${e.leave||''}"></label><label class="field full">Location<input id="evLocation" value="${e.location||''}"></label><label class="field full">Bring / reminder<input id="evBring" value="${e.bring||''}"></label><label class="field full">Notes<textarea id="evNotes">${e.notes||''}</textarea></label></div><div class="modal-actions"><button id="saveEventBtn" class="primary" type="button">Save event</button></div>`; $('#modal').showModal(); $('#saveEventBtn').onclick=()=>{Object.assign(e,{title:$('#evTitle').value.trim(),person:$('#evPerson').value,type:$('#evType').value,date:$('#evDate').value,time:$('#evTime').value,end:$('#evEnd').value,leave:$('#evLeave').value,location:$('#evLocation').value.trim(),bring:$('#evBring').value.trim(),notes:$('#evNotes').value.trim()});if(!e.title||!e.date)return;if(isNew)data.events.push(e);save();$('#modal').close();render()}
}
function bind(){
  document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{view=b.dataset.go;render()});
  document.querySelectorAll('.task-check').forEach(x=>x.onchange=()=>{data.tasks.find(t=>t.id==x.dataset.id).done=x.checked;save();render()});
  document.querySelectorAll('.staple-check').forEach(x=>x.onchange=()=>{data.staples.find(t=>t.id==x.dataset.id).need=x.checked;save();render()});
  document.querySelectorAll('.qty').forEach(x=>x.onchange=()=>{data.staples.find(t=>t.id==x.dataset.id).qty=+x.value||1;save()});
  document.querySelectorAll('.meal-select').forEach(x=>x.onchange=()=>{data.mealPlan[x.dataset.date]=x.value;save();render()});
  document.querySelectorAll('.color').forEach(x=>x.onchange=()=>{data.settings[x.dataset.person.toLowerCase()+'Color']=x.value;save();render()});
  document.querySelectorAll('.payment-check').forEach(x=>x.onchange=()=>{data.payments.find(p=>p.id==x.dataset.id).paid=x.checked;save();render()});
  document.querySelectorAll('.edit-event').forEach(x=>x.onclick=()=>openEventEditor(x.dataset.id)); document.querySelectorAll('.delete-event').forEach(x=>x.onclick=()=>{if(confirm('Delete this event?')){data.events=data.events.filter(e=>e.id!=x.dataset.id);save();render()}});
  document.querySelectorAll('.delete-staple').forEach(x=>x.onclick=()=>{if(confirm('Delete this staple?')){data.staples=data.staples.filter(e=>e.id!=x.dataset.id);save();render()}}); document.querySelectorAll('.edit-staple').forEach(x=>x.onclick=()=>{let a=data.staples.find(e=>e.id==x.dataset.id),v=prompt('Staple name',a.name);if(v){a.name=v.trim();save();render()}});
  document.querySelectorAll('.delete-meal').forEach(x=>x.onclick=()=>{if(confirm('Delete this meal?')){data.meals=data.meals.filter(e=>e.id!=x.dataset.id);save();render()}}); document.querySelectorAll('.edit-meal').forEach(x=>x.onclick=()=>{let a=data.meals.find(e=>e.id==x.dataset.id),n=prompt('Meal name',a.name);if(!n)return;a.name=n.trim();a.ingredients=prompt('Ingredients',a.ingredients||'')||'';a.recipe=prompt('Recipe / instructions',a.recipe||'')||'';save();render()});
  document.querySelectorAll('.delete-payment').forEach(x=>x.onclick=()=>{if(confirm('Delete payment?')){data.payments=data.payments.filter(e=>e.id!=x.dataset.id);save();render()}}); document.querySelectorAll('.edit-payment').forEach(x=>x.onclick=()=>{let a=data.payments.find(e=>e.id==x.dataset.id);a.name=prompt('Payment name',a.name)||a.name;a.day=+(prompt('Due day',a.day)||a.day);a.amount=prompt('Amount (optional)',a.amount||'')||'';save();render()});
  document.querySelectorAll('.delete-task').forEach(x=>x.onclick=()=>{if(confirm('Delete task?')){data.tasks=data.tasks.filter(e=>e.id!=x.dataset.id);save();render()}}); document.querySelectorAll('.edit-task').forEach(x=>x.onclick=()=>{let a=data.tasks.find(e=>e.id==x.dataset.id);a.name=prompt('Task',a.name)||a.name;a.due=prompt('Due date YYYY-MM-DD',a.due)||a.due;a.repeat=prompt('Repeat',a.repeat)||a.repeat;save();render()});
  document.querySelectorAll('.custody-toggle').forEach(x=>x.onclick=()=>{let d=x.dataset.date,def=(()=>{let old=data.settings.custodyOverrides[d];delete data.settings.custodyOverrides[d];let v=custodyForDate(d);if(old)data.settings.custodyOverrides[d]=old;return v})();let cur=custodyForDate(d);data.settings.custodyOverrides[d]=(cur.includes('Dad')&&!cur.includes('Mom'))?'Mom':'Dad';if(data.settings.custodyOverrides[d]===def)delete data.settings.custodyOverrides[d];save();render()});
  $('#addEvent')&&($('#addEvent').onclick=()=>openEventEditor()); $('#prevMonth')&&($('#prevMonth').onclick=()=>{calCursor.setMonth(calCursor.getMonth()-1);render()}); $('#nextMonth')&&($('#nextMonth').onclick=()=>{calCursor.setMonth(calCursor.getMonth()+1);render()});
  $('#addStaple')&&($('#addStaple').onclick=()=>simplePrompt('Add staple','Staple name',v=>{data.staples.push({id:Date.now(),name:v,qty:1,need:true});save();render()})); $('#addMeal')&&($('#addMeal').onclick=()=>simplePrompt('Add meal','Meal name',v=>{data.meals.push({id:Date.now(),name:v,ingredients:'',recipe:''});save();render()}));
  $('#addPayment')&&($('#addPayment').onclick=()=>{let n=prompt('Payment name');if(!n)return;data.payments.push({id:Date.now(),name:n,day:+(prompt('Due day','1')||1),amount:prompt('Amount (optional)','')||'',paid:false});save();render()}); $('#addTask')&&($('#addTask').onclick=()=>{let n=prompt('Task name');if(!n)return;data.tasks.push({id:Date.now(),name:n,due:prompt('Due date YYYY-MM-DD',addDays(1))||addDays(1),done:false,repeat:prompt('Repeat','Weekly')||'None'});save();render()});
  $('#copyList')&&($('#copyList').onclick=async()=>{let s=data.staples.filter(x=>x.need).map(x=>`${x.name}${x.qty>1?` x${x.qty}`:''}`).join('\n');await navigator.clipboard.writeText(s);alert('Shopping list copied.')}); $('#lock')&&($('#lock').onclick=()=>{localStorage.removeItem('familyHubUnlocked');localStorage.removeItem('familyHubPin');sessionStorage.removeItem('familyHubPin');location.reload()})
}
eventForm=()=>openEventEditor();
normalizeV11(); localSave();
