// Budget 2.0 — paycheck-based budget + debt hub v247a
(function(){
  function ensure(){data.budget=data.budget||{};if(!data.budget.paycheckAmount&&data.budget.monthlyIncome)data.budget.paycheckAmount='';data.budget.payFrequency=data.budget.payFrequency||'biweekly';data.budget.nextPayday=data.budget.nextPayday||'';data.budget.spendingLimit=data.budget.spendingLimit||'';data.budgetExpenses=data.budgetExpenses||[];data.debts=data.debts||[];data.debtPayments=data.debtPayments||[]}
  const money=n=>'$'+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:0,maximumFractionDigits:2}), esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const dayms=86400000;
  function add(ds,n){let d=new Date(ds+'T12:00');d.setDate(d.getDate()+n);return iso(d)}
  function paydays(){ensure();let anchor=data.budget.nextPayday;if(!anchor)return [];let step=data.budget.payFrequency==='weekly'?7:14,start=new Date(anchor+'T12:00'),today=new Date(vegasToday()+'T12:00');while(start<today)start.setDate(start.getDate()+step);let out=[];for(let i=0;i<10;i++){out.push(iso(start));start.setDate(start.getDate()+step)}return out}
  function cycle(){let p=paydays(),today=vegasToday();if(!p.length)return {start:today,end:add(today,14),next:'',days:14};let next=p[0],step=data.budget.payFrequency==='weekly'?7:14,prev=add(next,-step);return {start:prev,end:add(next,-1),next,days:step}}
  function cycleExpenses(c){return data.budgetExpenses.filter(x=>x.date>=c.start&&x.date<=c.end)}
  function billInCycle(p,c){let d=+p.day||0;if(!d)return false;let cur=new Date(c.start+'T12:00'),end=new Date(c.end+'T12:00');while(cur<=end){if(cur.getDate()===Math.min(d,new Date(cur.getFullYear(),cur.getMonth()+1,0).getDate()))return true;cur.setDate(cur.getDate()+1)}return false}
  function totals(){ensure();let c=cycle(),income=+data.budget.paycheckAmount||0,bills=(data.payments||[]).filter(p=>billInCycle(p,c)).reduce((s,x)=>s+(+x.amount||0),0),monthlyMin=data.debts.reduce((s,x)=>s+(+x.minimum||0),0),debtMin=monthlyMin*(c.days/30.4375),spent=cycleExpenses(c).reduce((s,x)=>s+(+x.amount||0),0),left=income-bills-debtMin-spent;return {c,income,bills,debtMin,monthlyMin,spent,left}}
  function persist(){if(typeof save==='function')save();else localStorage.setItem('familyHubData',JSON.stringify(data))}
  function page(){ensure();$('#modal')?.close();let t=totals(),recent=cycleExpenses(t.c).slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,8),limit=+data.budget.spendingLimit||0,cycleLimit=limit?limit*(t.c.days/30.4375):0,used=cycleLimit?Math.min(100,t.spent/cycleLimit*100):0,next=t.c.next?fmtDate(t.c.next):'Not set';
    $('#dashboard').innerHTML=`<section class="card full budget2-page"><div class="budget2-head"><div><div class="eyebrow">MONEY</div><h2>Budget & Debt</h2><p class="meta">Built around each paycheck — including the months with an extra one.</p></div><div class="budget2-actions"><button id="budgetAddExpense" class="primary">＋ Expense</button><button id="budgetSetup">Paycheck setup</button></div></div>
</section>`;
    document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));document.querySelector('nav [data-action="more"]')?.classList.add('active')}
  function debtMarkup(){let bal=data.debts.reduce((s,d)=>s+(+d.balance||0),0),start=data.debts.reduce((s,d)=>s+(+d.startingBalance||+d.balance||0),0),pct=start?Math.max(0,Math.min(100,(1-bal/start)*100)):0;return `<div class="budget2-debt-total"><strong>${money(bal)}</strong><span>remaining across ${data.debts.length} account${data.debts.length===1?'':'s'}</span></div><div class="budget2-bar"><i style="width:${pct}%"></i></div><div class="budget2-debt-foot"><span>${pct.toFixed(0)}% paid down</span><span>${money(data.debts.reduce((s,d)=>s+(+d.minimum||0),0))}/mo minimums</span></div>`}
  function expense(id){ensure();let x=data.budgetExpenses.find(e=>e.id==id),fresh=!x;if(!x)x={id:Date.now(),name:'',amount:'',category:'Groceries',date:vegasToday()};$('#modalTitle').textContent=fresh?'Add expense':'Edit expense';$('#modalBody').innerHTML=`<div class="form-grid"><label class="field full">What was it?<input id="bexName" value="${esc(x.name)}" placeholder="Groceries, gas, lunch..."></label><label class="field">Amount<input id="bexAmount" type="number" min="0" step=".01" inputmode="decimal" value="${x.amount||''}" placeholder="0.00"></label><label class="field">Category<select id="bexCategory">${['Groceries','Gas','Dining','Kids','Fun','Household','Medical','Other'].map(c=>`<option ${x.category===c?'selected':''}>${c}</option>`).join('')}</select></label><label class="field">Date<input id="bexDate" type="date" value="${x.date}"></label></div><div class="modal-actions">${fresh?'<span></span>':'<button type="button" class="danger" id="bexDelete">Delete</button>'}<button type="button" class="primary" id="bexSave">Save expense</button></div>`;$('#modal').showModal();$('#bexSave').onclick=()=>{x.name=$('#bexName').value.trim();x.amount=$('#bexAmount').value;x.category=$('#bexCategory').value;x.date=$('#bexDate').value;if(!x.name||!(+x.amount>0))return alert('Add a name and amount.');if(fresh)data.budgetExpenses.push(x);persist();page()};$('#bexDelete')&&($('#bexDelete').onclick=()=>{data.budgetExpenses=data.budgetExpenses.filter(e=>e.id!=x.id);persist();page()})}
  function setup(){ensure();$('#modalTitle').textContent='Paycheck setup';$('#modalBody').innerHTML=`<p class="meta">Set this once. Family Hub will roll forward from the payday you enter and automatically handle 2-paycheck and 3-paycheck months.</p><div class="form-grid"><label class="field full">Take-home amount per paycheck<input id="budgetPaycheck" type="number" min="0" step=".01" inputmode="decimal" value="${data.budget.paycheckAmount||''}" placeholder="Amount deposited each payday"></label><label class="field">Pay schedule<select id="budgetFrequency"><option value="biweekly" ${data.budget.payFrequency==='biweekly'?'selected':''}>Every 2 weeks</option><option value="weekly" ${data.budget.payFrequency==='weekly'?'selected':''}>Every week</option></select></label><label class="field">Next payday<input id="budgetNextPayday" type="date" value="${data.budget.nextPayday||''}"></label><label class="field full">Monthly everyday spending target <span class="meta">(optional)</span><input id="budgetLimit" type="number" min="0" step=".01" inputmode="decimal" value="${data.budget.spendingLimit||''}" placeholder="Family Hub converts this to each pay period"></label></div><div class="modal-actions"><span></span><button type="button" class="primary" id="budgetSaveSetup">Save</button></div>`;$('#modal').showModal();$('#budgetSaveSetup').onclick=()=>{data.budget.paycheckAmount=$('#budgetPaycheck').value;data.budget.payFrequency=$('#budgetFrequency').value;data.budget.nextPayday=$('#budgetNextPayday').value;data.budget.spendingLimit=$('#budgetLimit').value;persist();page()}}
  function inject(){let menu=document.querySelector('.more-menu');if(!menu||menu.querySelector('[data-budget-open]'))return;let group=[...menu.querySelectorAll('.more-group')].find(g=>g.querySelector('.eyebrow')?.textContent.trim()==='MONEY'),grid=group?.querySelector('.more-grid');if(!grid)return;let b=document.createElement('button');b.type='button';b.className='more-destination';b.dataset.budgetOpen='1';b.innerHTML='<span class="more-icon">＄</span><span><b>Budget & Debt</b><small>Paycheck budget + paydown</small></span><i>›</i>';grid.prepend(b)}
  document.addEventListener('click',e=>{if(e.target.closest?.('[data-action="more"]'))setTimeout(inject,0);if(e.target.closest?.('[data-budget-open]'))page();if(e.target.closest?.('#budgetAddExpense,#budgetAddExpense2'))expense();if(e.target.closest?.('#budgetSetup'))setup();let x=e.target.closest?.('[data-budget-expense]');if(x)expense(+x.dataset.budgetExpense);if(e.target.closest?.('[data-budget-debt]'))document.querySelector('[data-debt-open]')?.click()});
  window.openBudget2=page;ensure();
})();