// Budget 2.0 — low-maintenance budget + debt hub v246a
(function(){
  function ensure(){data.budget=data.budget||{monthlyIncome:'',spendingLimit:'',categories:{Groceries:'',Gas:'',Dining:'',Kids:'',Fun:'',Other:''}};data.budgetExpenses=data.budgetExpenses||[];data.debts=data.debts||[];data.debtPayments=data.debtPayments||[]}
  const money=n=>'$'+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:0,maximumFractionDigits:2});
  const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function month(){return vegasToday().slice(0,7)}
  function expenses(){ensure();return data.budgetExpenses.filter(x=>(x.date||'').slice(0,7)===month())}
  function totals(){ensure();let income=+data.budget.monthlyIncome||0,bills=(data.payments||[]).reduce((s,x)=>s+(+x.amount||0),0),debtMin=data.debts.reduce((s,x)=>s+(+x.minimum||0),0),spent=expenses().reduce((s,x)=>s+(+x.amount||0),0),left=income-bills-debtMin-spent;return {income,bills,debtMin,spent,left}}
  function persist(){if(typeof save==='function')save();else localStorage.setItem('familyHubData',JSON.stringify(data))}
  function page(){ensure();$('#modal')?.close();let t=totals(),recent=expenses().slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,8),limit=+data.budget.spendingLimit||0,used=limit?Math.min(100,t.spent/limit*100):0;
    $('#dashboard').innerHTML=`<section class="card full budget2-page"><div class="budget2-head"><div><div class="eyebrow">MONEY</div><h2>Budget & Debt</h2><p class="meta">A simple picture of what came in, what has to go out, and what is safe to spend.</p></div><div class="budget2-actions"><button id="budgetAddExpense" class="primary">＋ Expense</button><button id="budgetSetup">Setup</button></div></div>
    <div class="budget2-safe"><small>LEFT AFTER BILLS, DEBT MINIMUMS & SPENDING</small><strong class="${t.left<0?'negative':''}">${money(t.left)}</strong><span>${t.income?'For '+new Date(vegasToday()+'T12:00').toLocaleDateString([],{month:'long'}):'Add monthly take-home pay to turn this on'}</span></div>
    <div class="budget2-flow"><div><span>Take-home</span><b>${money(t.income)}</b></div><i>−</i><div><span>Bills</span><b>${money(t.bills)}</b></div><i>−</i><div><span>Debt minimums</span><b>${money(t.debtMin)}</b></div><i>−</i><div><span>Everyday spending</span><b>${money(t.spent)}</b></div></div>
    <div class="budget2-grid"><div class="budget2-panel"><div class="budget2-panel-head"><div><h3>Everyday spending</h3><span class="meta">Just log purchases — no spreadsheet needed.</span></div><button id="budgetAddExpense2">＋ Add</button></div>${limit?`<div class="budget2-limit"><div><span>Monthly spending target</span><b>${money(t.spent)} / ${money(limit)}</b></div><div class="budget2-bar"><i style="width:${used}%"></i></div></div>`:''}<div class="budget2-recent">${recent.length?recent.map(x=>`<button class="budget2-expense" data-budget-expense="${x.id}"><span><b>${esc(x.name)}</b><small>${esc(x.category||'Other')} · ${fmtDate(x.date)}</small></span><strong>−${money(x.amount)}</strong></button>`).join(''):'<p class="muted">No spending logged this month. Add an expense when something comes up.</p>'}</div></div>
    <div class="budget2-panel budget2-debt"><div class="budget2-panel-head"><div><h3>Debt paydown</h3><span class="meta">Minimums are already included above.</span></div><button data-budget-debt>Open Debt</button></div>${debtMarkup()}</div></div></section>`;
    document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));document.querySelector('nav [data-action="more"]')?.classList.add('active');
  }
  function debtMarkup(){let bal=data.debts.reduce((s,d)=>s+(+d.balance||0),0),start=data.debts.reduce((s,d)=>s+(+d.startingBalance||+d.balance||0),0),pct=start?Math.max(0,Math.min(100,(1-bal/start)*100)):0;return `<div class="budget2-debt-total"><strong>${money(bal)}</strong><span>remaining across ${data.debts.length} account${data.debts.length===1?'':'s'}</span></div><div class="budget2-bar"><i style="width:${pct}%"></i></div><div class="budget2-debt-foot"><span>${pct.toFixed(0)}% paid down</span><span>${money(data.debts.reduce((s,d)=>s+(+d.minimum||0),0))}/mo minimums</span></div>`}
  function expense(id){ensure();let x=data.budgetExpenses.find(e=>e.id==id),fresh=!x;if(!x)x={id:Date.now(),name:'',amount:'',category:'Groceries',date:vegasToday()};$('#modalTitle').textContent=fresh?'Add expense':'Edit expense';$('#modalBody').innerHTML=`<div class="form-grid"><label class="field full">What was it?<input id="bexName" value="${esc(x.name)}" placeholder="Groceries, gas, lunch..."></label><label class="field">Amount<input id="bexAmount" type="number" min="0" step=".01" inputmode="decimal" value="${x.amount||''}" placeholder="0.00"></label><label class="field">Category<select id="bexCategory">${['Groceries','Gas','Dining','Kids','Fun','Household','Medical','Other'].map(c=>`<option ${x.category===c?'selected':''}>${c}</option>`).join('')}</select></label><label class="field">Date<input id="bexDate" type="date" value="${x.date}"></label></div><div class="modal-actions">${fresh?'<span></span>':'<button type="button" class="danger" id="bexDelete">Delete</button>'}<button type="button" class="primary" id="bexSave">Save expense</button></div>`;$('#modal').showModal();$('#bexSave').onclick=()=>{x.name=$('#bexName').value.trim();x.amount=$('#bexAmount').value;x.category=$('#bexCategory').value;x.date=$('#bexDate').value;if(!x.name||!(+x.amount>0))return alert('Add a name and amount.');if(fresh)data.budgetExpenses.push(x);persist();page()};$('#bexDelete')&&($('#bexDelete').onclick=()=>{data.budgetExpenses=data.budgetExpenses.filter(e=>e.id!=x.id);persist();page()})}
  function setup(){ensure();$('#modalTitle').textContent='Budget setup';$('#modalBody').innerHTML=`<p class="meta">Keep this simple. Two numbers are enough to start; your existing Monthly Payments and Debt accounts fill in the rest.</p><div class="form-grid"><label class="field full">Monthly take-home pay<input id="budgetIncome" type="number" min="0" step=".01" inputmode="decimal" value="${data.budget.monthlyIncome||''}" placeholder="After-tax income"></label><label class="field full">Everyday spending target <span class="meta">(optional)</span><input id="budgetLimit" type="number" min="0" step=".01" inputmode="decimal" value="${data.budget.spendingLimit||''}" placeholder="Groceries + gas + eating out + fun..."></label></div><div class="modal-actions"><span></span><button type="button" class="primary" id="budgetSaveSetup">Save</button></div>`;$('#modal').showModal();$('#budgetSaveSetup').onclick=()=>{data.budget.monthlyIncome=$('#budgetIncome').value;data.budget.spendingLimit=$('#budgetLimit').value;persist();page()}}
  function inject(){let menu=document.querySelector('.more-menu');if(!menu||menu.querySelector('[data-budget-open]'))return;let group=[...menu.querySelectorAll('.more-group')].find(g=>g.querySelector('.eyebrow')?.textContent.trim()==='MONEY'),grid=group?.querySelector('.more-grid');if(!grid)return;let b=document.createElement('button');b.type='button';b.className='more-destination';b.dataset.budgetOpen='1';b.innerHTML='<span class="more-icon">＄</span><span><b>Budget & Debt</b><small>Simple spending + paydown</small></span><i>›</i>';grid.prepend(b)}
  document.addEventListener('click',e=>{if(e.target.closest?.('[data-action="more"]'))setTimeout(inject,0);if(e.target.closest?.('[data-budget-open]'))page();if(e.target.closest?.('#budgetAddExpense,#budgetAddExpense2'))expense();if(e.target.closest?.('#budgetSetup'))setup();let x=e.target.closest?.('[data-budget-expense]');if(x)expense(+x.dataset.budgetExpense);if(e.target.closest?.('[data-budget-debt]')){document.querySelector('[data-debt-open]')?.click()}});
  window.openBudget2=page;ensure();
})();