// Home-only dashboard editor — pinned above motivation v211a
(function(){
const items=[['glance','.family-glance'],['next','.family-next'],['today','.family-today'],['weather','.weather-card'],['habits','.habits-card']];
function r(){return document.querySelector('#dashboard')}
function home(){try{return (window.view||view)==='home'}catch(e){return false}}
function findBuiltins(root){let out={};items.forEach(([id,sel])=>{let el=root.querySelector(sel);if(el)out[id]=el});[...root.querySelectorAll('.card')].forEach(el=>{let h=(el.querySelector('h2')?.textContent||'').trim().toLowerCase();if(h==='weather'&&!out.weather)out.weather=el;if(h==='habits'&&!out.habits)out.habits=el});return out}
function current(found){data.settings=data.settings||{};let available=Object.keys(found),saved=Array.isArray(data.settings.dashboardOrder)?data.settings.dashboardOrder:[];let o=saved.filter(x=>available.includes(x));available.forEach(x=>{if(!o.includes(x))o.push(x)});return o}
function ensure(){let root=r();if(!root)return;let bar=root.querySelector('.dashboard-editbar');if(!bar){bar=document.createElement('div');bar.className='dashboard-editbar';bar.innerHTML='<button type="button" class="mini secondary" data-dashboard-edit>↕ Edit dashboard</button>'}if(root.firstElementChild!==bar)root.insertAdjacentElement('afterbegin',bar)}
function apply(){if(!home())return;let root=r();if(!root)return;ensure();let found=findBuiltins(root),o=current(found),anchor=root.querySelector('.attention-card');o.forEach(id=>{let el=found[id];if(!el)return;el.dataset.dashboardTile=id;if(anchor){anchor.insertAdjacentElement('afterend',el);anchor=el}else root.appendChild(el)});ensure();if(root.classList.contains('dashboard-editing'))decorate()}
function decorate(){let root=r();if(!root)return;root.querySelectorAll('.dash-movers').forEach(x=>x.remove());if(!root.classList.contains('dashboard-editing'))return;let found=findBuiltins(root),o=current(found);o.forEach((id,i)=>{let el=found[id];if(!el)return;let d=document.createElement('div');d.className='dash-movers';d.innerHTML='<span>Move</span><button type="button" aria-label="Move up" data-dashboard-move="'+id+'" data-dir="-1" '+(i===0?'disabled':'')+'>↑</button><button type="button" aria-label="Move down" data-dashboard-move="'+id+'" data-dir="1" '+(i===o.length-1?'disabled':'')+'>↓</button>';el.prepend(d)})}
function toggle(){let root=r(),bar=root?.querySelector('.dashboard-editbar');if(!root||!bar)return;let on=root.classList.toggle('dashboard-editing');bar.innerHTML=on?'<span class="meta">Reorder Home tiles</span><button type="button" class="mini" data-dashboard-done>Done</button>':'<button type="button" class="mini secondary" data-dashboard-edit>↕ Edit dashboard</button>';decorate()}
function move(id,dir){let root=r(),found=findBuiltins(root),o=current(found),i=o.indexOf(id),j=i+Number(dir);if(i<0||j<0||j>=o.length)return;[o[i],o[j]]=[o[j],o[i]];data.settings.dashboardOrder=o;save();let anchor=root.querySelector('.attention-card');o.forEach(k=>{let el=found[k];if(anchor){anchor.insertAdjacentElement('afterend',el);anchor=el}else root.appendChild(el)});ensure();decorate()}
document.addEventListener('click',e=>{if(e.target.closest?.('[data-dashboard-edit],[data-dashboard-done]')){e.preventDefault();toggle();return}let b=e.target.closest?.('[data-dashboard-move]');if(b){e.preventDefault();e.stopPropagation();move(b.dataset.dashboardMove,b.dataset.dir)}});let obs=new MutationObserver(()=>{if(home())setTimeout(apply,0)});document.addEventListener('DOMContentLoaded',()=>{let root=r();if(root)obs.observe(root,{childList:true});setTimeout(apply,30)});setInterval(()=>{if(home())apply()},500);
})();
