// Family Dashboard 2.0 — v197a
(function(){
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ft(t){if(!t)return 'All day';let [h,m]=t.split(':').map(Number),a=h>=12?'PM':'AM';h=h%12||12;return h+(m?':'+String(m).padStart(2,'0'):'')+' '+a}
function add(ds,n){let d=new Date(ds+'T12:00');d.setDate(d.getDate()+n);return iso(d)}
function due(t,ds){if(t.done)return false;if(t.taskMode==='cycle')return typeof taskDueToday==='function'?taskDueToday(t):choreStatus(t).startsWith('Due now');return !!t.due&&t.due<=ds}
function nextEvents(ds){let out=[];for(let n=0;n<7&&out.length<4;n++){let d=add(ds,n);(typeof eventsForDate==='function'?eventsForDate(d):[]).forEach(e=>out.push({...e,_date:d,_days:n}))}return out.sort((a,b)=>(a._date+(a.time||'99:99')).localeCompare(b._date+(b.time||'99:99'))).slice(0,4)}
function dashboard(){let ds=vegasToday(),events=nextEvents(ds),tasks=(data.tasks||[]).filter(t=>due(t,ds)),habits=(data.habits||[]).filter(h=>(h.trackerType||'habit')==='habit'&&habitApplies(h,ds)),done=habits.filter(h=>data.habitLog?.[ds]?.[h.id]).length,meal=data.mealPlan?.[ds],shop=(data.staples||[]).filter(x=>x.need).length,people=['Richard','Timothy','Olivia'];
return '<section class="card full family-glance"><div class="card-head"><div><div class="eyebrow">FAMILY DASHBOARD</div><h2>At a glance</h2><div class="meta">What the family has going on right now</div></div></div><div class="family-glance-grid"><button data-dash-go="calendar"><span>📅</span><b>'+events.length+'</b><small>upcoming</small></button><button data-dash-go="tasks"><span>✅</span><b>'+tasks.length+'</b><small>tasks due</small></button><button data-dash-go="habits"><span>⭐</span><b>'+done+'/'+habits.length+'</b><small>habits</small></button><button data-dash-go="shop"><span>🛒</span><b>'+shop+'</b><small>to buy</small></button></div></section><section class="card family-next"><div class="card-head"><div><h2>Up next</h2><div class="meta">Next 7 days</div></div><button data-dash-go="calendar">Calendar</button></div><div class="family-next-list">'+(events.map(e=>'<button data-dash-go="calendar" class="family-next-row"><span class="family-person-dot" style="background:'+personColor(e.person)+'"></span><span><b>'+esc(e.title)+'</b><small>'+(e._days===0?'Today':e._days===1?'Tomorrow':fmtDate(e._date))+' · '+ft(e.time)+(e.person?' · '+esc(e.person):'')+'</small></span><i>›</i></button>').join('')||'<div class="family-empty">Nothing scheduled in the next 7 days.</div>')+'</div></section><section class="card family-today"><div class="card-head"><div><h2>Today</h2><div class="meta">Tasks, dinner & family</div></div><button data-dash-go="today">Open Today</button></div><div class="family-today-block"><span>✅</span><div><b>'+tasks.length+' task'+(tasks.length===1?'':'s')+' due</b><small>'+(tasks.slice(0,2).map(t=>esc(t.name)).join(' · ')||'Nothing due right now')+'</small></div></div><div class="family-today-block"><span>🍽️</span><div><b>Dinner</b><small>'+esc(meal||'Nothing planned yet')+'</small></div></div><div class="family-people">'+people.map(p=>'<span><i style="background:'+personColor(p)+'"></i>'+p+'</span>').join('')+'</div></section>'}
function inject(){if((window.view||view)!=='home')return;let root=document.querySelector('#dashboard');if(!root||root.querySelector('.family-glance'))return;let attention=root.querySelector('.attention-card');if(attention)attention.insertAdjacentHTML('afterend',dashboard());else root.insertAdjacentHTML('afterbegin',dashboard())}
function go(v){if(v==='today'){document.querySelector('[data-view="today"]')?.click();return}let b=document.querySelector('[data-view="'+v+'"]');if(b){b.click();return}view=v;render()}
document.addEventListener('click',e=>{let b=e.target.closest?.('[data-dash-go]');if(b)go(b.dataset.dashGo)});let old=window.render;if(typeof old==='function'){window.render=function(){let r=old.apply(this,arguments);setTimeout(inject,1);return r}}else setInterval(inject,500);setTimeout(inject,1)
})();
