// Home-only dashboard editor — fixed placement + per-tile controls v212a
(function(){
const known=[['glance','.family-glance'],['next','.family-next'],['today','.family-today']];
function root(){return document.querySelector('#dashboard')}
function home(){try{return (window.view||view)==='home'}catch(e){return false}}
function motivation(r){return [...r.children].find(el=>el.classList?.contains('motivation-card')||el.classList?.contains('daily-card')||/running on empty|remember today|today.?s verse/i.test(el.textContent||''))}
function tiles(r){let out={};known.forEach(([id,sel])=>{let el=r.querySelector(sel);if(el)out[id]=el});[...r.querySelectorAll(':scope > .card')].forEach(el=>{if(el.classList.contains('attention-card')||Object.values(out).includes(el))return;let h=(el.querySelector('h2')?.textContent||'').trim().toLowerCase();if(h==='weather')out.weather=el;else if(h==='habits')out.habits=el});return out}
function order(found){data.settings=data.settings||{};let available=Object.keys(found),saved=Array.isArray(data.settings.dashboardOrder)?data.settings.dashboardOrder:[];let o=saved.filter(x=>available.includes(x));available.forEach(x=>{if(!o.includes(x))o.push(x)});return o}
function ensureBar(){let r=root();if(!r)return;let bar=r.querySelector('.dashboard-editbar');if(!bar){bar=document.createElement('div');bar.className='dashboard-editbar';bar.innerHTML='<button type="button" class="mini secondary" data-dashboard-edit>↕ Edit dashboard</button>'}let mot=motivation(r);if(mot){if(mot.previousElementSibling!==bar)mot.insertAdjacentElement('beforebegin',bar)}else if(r.firstElementChild!==bar)r.prepend(bar)}
function applyOrder(){if(!home())return;let r=root();if(!r)return;ensureBar();let found=tiles(r),o=order(found),anchor=r.querySelector('.attention-card');o.forEach(id=>{let el=found[id];if(!el)return;el.dataset.dashboardTile=id;if(anchor){anchor.insertAdjacentElement('afterend',el);anchor=el}else r.appendChild(el)});ensureBar();if(r.classList.contains('dashboard-editing'))decorate()}
function decorate(){let r=root();if(!r)return;r.querySelectorAll('.dash-movers').forEach(x=>x.remove());if(!r.classList.contains('dashboard-editing'))return;let found=tiles(r),o=order(found);o.forEach((id,i)=>{let el=found[id];if(!el)return;el.style.position='relative';let d=document.createElement('div');d.className='dash-movers';d.innerHTML='<span>Move</span><button type="button" aria-label="Move '+id+' up" data-dashboard-move="'+id+'" data-dir="-1" '+(i===0?'disabled':'')+'>↑</button><button type="button" aria-label="Move '+id+' down" data-dashboard-move="'+id+'" data-dir="1" '+(i===o.length-1?'disabled':'')+'>↓</button>';el.appendChild(d)})}
function toggle(){let r=root();if(!r)return;ensureBar();let bar=r.querySelector('.dashboard-editbar'),on=r.classList.toggle('dashboard-editing');bar.innerHTML=on?'<span class="meta">Reorder Home tiles</span><button type="button" class="mini" data-dashboard-done>Done</button>':'<button type="button" class="mini secondary" data-dashboard-edit>↕ Edit dashboard</button>';decorate()}
function move(id,dir){let r=root(),found=tiles(r),o=order(found),i=o.indexOf(id),j=i+Number(dir);if(i<0||j<0||j>=o.length)return;[o[i],o[j]]=[o[j],o[i]];data.settings.dashboardOrder=o;save();let anchor=r.querySelector('.attention-card');o.forEach(k=>{let el=found[k];if(anchor){anchor.insertAdjacentElement('afterend',el);anchor=el}else r.appendChild(el)});ensureBar();decorate()}
document.addEventListener('click',e=>{if(e.target.closest?.('[data-dashboard-edit],[data-dashboard-done]')){e.preventDefault();toggle();return}let b=e.target.closest?.('[data-dashboard-move]');if(b){e.preventDefault();e.stopPropagation();move(b.dataset.dashboardMove,b.dataset.dir)}});let busy=false;function sync(){if(busy||!home())return;busy=true;requestAnimationFrame(()=>{applyOrder();busy=false})}let obs=new MutationObserver(sync);document.addEventListener('DOMContentLoaded',()=>{let r=root();if(r)obs.observe(r,{childList:true});setTimeout(sync,50)});setInterval(sync,1000);
})();
