// Additional Home dashboard tiles — v217a
(function(){
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function isHome(){try{return (window.view||view)==='home'}catch(e){return false}}
function add(ds,n){let d=new Date(ds+'T12:00');d.setDate(d.getDate()+n);return iso(d)}
function ft(t){if(!t)return 'All day';let [h,m]=t.split(':').map(Number),a=h>=12?'PM':'AM';h=h%12||12;return h+(m?':'+String(m).padStart(2,'0'):'')+' '+a}
function go(v){if(v==='sports'&&typeof window.openSportsHub==='function'){window.openSportsHub();return}if(v==='wellness'&&typeof window.openWellness==='function'){window.openWellness();return}if(v==='debt'&&typeof window.openDebt==='function'){window.openDebt();return}let b=document.querySelector('[data-view="'+v+'"]');if(b)b.click();else{try{view=v;render()}catch(e){}}}
function sports(ds){let ev=[];for(let i=0;i<14;i++){let d=add(ds,i);(typeof eventsForDate==='function'?eventsForDate(d):[]).filter(e=>/practice|game|sports/i.test((e.type||'')+' '+(e.title||''))).forEach(e=>ev.push({...e,_date:d,_days:i}))}ev.sort((a,b)=>(a._date+(a.time||'99:99')).localeCompare(b._date+(b.time||'99:99')));let next=ev[0];return '<section class="card dash-extra dash-sports" data-dashboard-tile="sports"><div class="dash-card-kicker"><span>⚾</span><b>SPORTS</b></div><div class="card-head"><div><h2>Sports</h2><div class="meta">Next 14 days</div></div><span class="pill">'+ev.length+' upcoming</span></div>'+(next?'<button class="dash-extra-main" data-extra-go="sports"><span class="family-person-dot" style="background:'+personColor(next.person)+'"></span><span><b>'+esc(next.title)+'</b><small>'+(next._days===0?'Today':next._days===1?'Tomorrow':fmtDate(next._date))+' · '+ft(next.time)+' · '+esc(next.person||'Family')+'</small></span><i>›</i></button>':'<div class="family-empty">No practices or games coming up.</div>')+'<button class="dash-extra-link" data-extra-go="sports">Open Sports</button></section>'}
function wellness(ds){let mood=data.moodLog?.[ds],smoke=data.smokingLog?.[ds]||data.smokeLog?.[ds],period=data.periodLog?.[ds],bits=[];if(mood)bits.push('Mood logged');if(smoke)bits.push('Smoking logged');if(period)bits.push('Period logged');return '<section class="card dash-extra dash-wellness" data-dashboard-tile="wellness"><div class="dash-card-kicker"><span>♡</span><b>WELLNESS</b></div><div class="card-head"><div><h2>Wellness</h2><div class="meta">Today’s check-ins</div></div><span class="pill">'+bits.length+' logged</span></div><div class="dash-extra-stat"><b>'+bits.length+'</b><span>wellness check-in'+(bits.length===1?'':'s')+' today</span></div><div class="meta dash-extra-note">'+(bits.length?esc(bits.join(' · ')):'Nothing logged yet today')+'</div><button class="dash-extra-link" data-extra-go="wellness">Open Wellness</button></section>'}
function debt(){let rows=data.debts||data.debtAccounts||[],current=rows.reduce((s,x)=>s+Number(x.balance??x.currentBalance??0),0),start=rows.reduce((s,x)=>s+Number(x.startingBalance??x.originalBalance??x.balance??0),0),paid=Math.max(0,start-current),pct=start?Math.min(100,Math.round(paid/start*100)):0;return '<section class="card dash-extra dash-debt" data-dashboard-tile="debt-pay-down"><div class="dash-card-kicker"><span>💳</span><b>DEBT PAY DOWN</b></div><div class="card-head"><div><h2>Debt progress</h2><div class="meta">'+rows.length+' account'+(rows.length===1?'':'s')+' tracked</div></div><span class="pill">'+pct+'%</span></div><div class="dash-extra-stat"><b>$'+Math.round(current).toLocaleString()+'</b><span>remaining balance</span></div><div class="dash-progress"><i style="width:'+pct+'%"></i></div><button class="dash-extra-link" data-extra-go="debt">Open Debt</button></section>'}
function inject(){if(!isHome())return;let root=document.querySelector('#dashboard');if(!root||root.querySelector('.dash-sports'))return;let ds=vegasToday(),html=sports(ds)+wellness(ds)+debt();root.insertAdjacentHTML('beforeend',html);document.dispatchEvent(new CustomEvent('family-dashboard-ready'))}
document.addEventListener('click',e=>{let b=e.target.closest?.('[data-extra-go]');if(b){e.preventDefault();go(b.dataset.extraGo)}});document.addEventListener('DOMContentLoaded',()=>setTimeout(inject,80));document.addEventListener('family-dashboard-ready',()=>setTimeout(inject,20));setInterval(inject,1200);
})();
