// Family Dashboard 2.0 — stable renderer v209a
(function(){
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ft(t){return window.familyHubTime.format(t)}
function add(ds,n){let d=new Date(ds+'T12:00');d.setDate(d.getDate()+n);return iso(d)}
function due(t,ds){if(t.done)return false;if(t.taskMode==='cycle')return typeof taskDueToday==='function'?taskDueToday(t):choreStatus(t).startsWith('Due now');return !!t.due&&t.due<=ds}
function nextEvents(ds){let out=[];for(let n=0;n<7;n++){let d=add(ds,n);(typeof eventsForDate==='function'?eventsForDate(d):[]).forEach(e=>out.push({...e,_date:d,_days:n}))}return out.sort((a,b)=>(a._date+(a.time||'99:99')).localeCompare(b._date+(b.time||'99:99')))}
function taskColor(t){let p=t.assigned||'Everyone';if(['Richard','Timothy','Olivia'].includes(p))return personColor(p);return t.category==='Work'?'#7183a3':t.category==='School'||t.category==='Sports'?'#d6aa5c':'#8b7b67'}
function taskMeta(t,ds){let bits=[];if(t.taskMode!=='cycle'&&t.due<ds)bits.push('Overdue');bits.push(t.assigned||'Everyone');bits.push(t.category||'Household');if(t.taskMode==='cycle')bits.push(t.cycle||'Repeating');return bits.join(' · ')}
function dashboard(){let ds=vegasToday(),events=nextEvents(ds),tasks=(data.tasks||[]).filter(t=>due(t,ds)).sort((a,b)=>{let ao=a.taskMode!=='cycle'&&a.due<ds?0:1,bo=b.taskMode!=='cycle'&&b.due<ds?0:1;return ao-bo||String(a.due||'').localeCompare(String(b.due||''))||String(a.name||'').localeCompare(String(b.name||''))}),overdue=tasks.filter(t=>t.taskMode!=='cycle'&&t.due<ds).length,habits=(data.habits||[]).filter(h=>(h.trackerType||'habit')==='habit'&&habitApplies(h,ds)),done=habits.filter(h=>data.habitLog?.[ds]?.[h.id]).length,meal=data.mealPlan?.[ds],shop=(data.staples||[]).filter(x=>x.need).length,people=['Richard','Timothy','Olivia'];
return '<section class="card full family-glance"><div class="card-head"><div><div class="eyebrow">FAMILY DASHBOARD</div><h2>At a glance</h2><div class="meta">What the family has going on right now</div></div></div><div class="family-glance-grid"><button data-dash-go="calendar"><span>📅</span><b>'+events.length+'</b><small>next 7 days</small></button><button data-dash-go="tasks"><span>✅</span><b>'+tasks.length+'</b><small>'+(overdue?overdue+' overdue':'tasks due')+'</small></button><button data-dash-go="habits"><span>⭐</span><b>'+done+'/'+habits.length+'</b><small>habits</small></button><button data-dash-go="shop"><span>🛒</span><b>'+shop+'</b><small>to buy</small></button></div></section><section class="card family-next"><div class="card-head"><div><h2>Up next</h2><div class="meta">Everything scheduled in the next 7 days</div></div><button data-dash-go="calendar">Calendar</button></div><div class="family-next-list">'+(events.map(e=>'<button data-dash-go="calendar" class="family-next-row"><span class="hv-event-time">'+ft(e.time)+'</span><span class="hv-event-copy" style="--event-person:'+personColor(e.person)+'"><b>'+esc(e.title)+'</b><small>'+(e._days===0?'Today':e._days===1?'Tomorrow':fmtDate(e._date))+(e.location?' · '+esc(e.location):'')+(e.person?' · '+esc(e.person):'')+'</small></span><i>›</i></button>').join('')||'<div class="family-empty">Nothing scheduled in the next 7 days.</div>')+'</div></section><section class="card family-today"><div class="card-head"><div><h2>Today</h2><div class="meta">'+(tasks.length?tasks.length+' thing'+(tasks.length===1?'':'s')+' to get done':'Everything that needs to get done')+'</div></div><button data-dash-go="today">Open Today</button></div><div class="family-today-tasks">'+(tasks.map(t=>'<div class="family-today-task '+(t.taskMode!=='cycle'&&t.due<ds?'is-overdue':'')+'"><button class="family-task-check" data-dash-complete="'+t.id+'" aria-label="Complete '+esc(t.name)+'">✓</button><div class="family-task-main" data-dash-go="tasks" role="button" tabindex="0"><span class="family-person-dot" style="background:'+taskColor(t)+'"></span><span class="family-task-copy"><b>'+esc(t.name)+'</b><small>'+esc(taskMeta(t,ds))+'</small></span><i>›</i></div></div>').join('')||'<div class="family-empty">Nothing due right now.</div>')+'</div><div class="family-today-block"><span>🍽️</span><div><b>Dinner</b><small>'+esc(meal||'Nothing planned yet')+'</small></div></div><div class="family-people">'+people.map(p=>'<span><i style="background:'+personColor(p)+'"></i>'+p+'</span>').join('')+'</div></section>'}
function removeOldComingUp(root){let cards=[...root.querySelectorAll('.card')];cards.forEach(c=>{if(c.classList.contains('family-next')||c.classList.contains('family-glance')||c.classList.contains('family-today')||c.classList.contains('attention-card'))return;let h=c.querySelector('h2');if(h&&/coming up/i.test(h.textContent||''))c.remove()})}
function inject(){if((window.view||view)!=='home')return;let root=document.querySelector('#dashboard');if(!root)return;removeOldComingUp(root);if(root.querySelector('.family-glance'))return;let attention=root.querySelector('.attention-card');if(attention)attention.insertAdjacentHTML('afterend',dashboard());else root.insertAdjacentHTML('afterbegin',dashboard());removeOldComingUp(root);document.dispatchEvent(new CustomEvent('family-dashboard-ready'))}
function go(v){if(v==='today'){document.querySelector('[data-view="today"]')?.click();return}let b=document.querySelector('[data-view="'+v+'"]');if(b){b.click();return}view=v;render()}
function complete(id){let t=(data.tasks||[]).find(x=>String(x.id)===String(id));if(!t)return;if(t.taskMode==='cycle'){let ds=vegasToday();data.taskLog=data.taskLog||{};let log=data.taskLog[ds];if(Array.isArray(log))log.push({id:t.id});else{data.taskLog[ds]=log&&typeof log==='object'?log:{};data.taskLog[ds][t.id]=true}t.lastCompleted=ds}else t.done=true;save();render()}
document.addEventListener('click',e=>{let c=e.target.closest?.('[data-dash-complete]');if(c){e.preventDefault();e.stopPropagation();complete(c.dataset.dashComplete);return}let b=e.target.closest?.('[data-dash-go]');if(b)go(b.dataset.dashGo)});document.addEventListener('keydown',e=>{let b=e.target.closest?.('.family-task-main[data-dash-go]');if(b&&(e.key==='Enter'||e.key===' ')){e.preventDefault();go(b.dataset.dashGo)}});let old=window.render;if(typeof old==='function'){window.render=function(){let r=old.apply(this,arguments);inject();return r}}else setInterval(inject,500);setTimeout(inject,1)
})();
