// Additional Home dashboard tiles — v222a
(function(){
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function root(){return document.querySelector('#dashboard')}
function syncSurface(){let r=root();if(!r)return '';if(r.querySelector(':scope > .sports-page-full'))r.dataset.fhSurface='sports';else if(r.querySelector(':scope > .debt-page'))r.dataset.fhSurface='debt';else if(r.querySelector(':scope > .family-glance'))r.dataset.fhSurface='home';else r.dataset.fhSurface='other';return r.dataset.fhSurface}
function homeMounted(){return syncSurface()==='home'}
function ft(t){return window.familyHubTime.format(t)}
function openInjected(selector){let more=document.querySelector('[data-action="more"]');if(!more)return;more.click();setTimeout(()=>{let b=document.querySelector(selector);if(b)b.click()},80)}
function go(v){if(v==='sports'){openInjected('[data-sports-open]');return}if(v==='debt'){openInjected('[data-debt-open]');return}if(v==='wellness'){try{view='habits';render();window.scrollTo({top:0,behavior:'smooth'})}catch(e){}return}}
function sportEvents(){let out=[];(data.events||[]).filter(e=>e.type==='Game'||e.sportEvent&&e.type==='Game').forEach(e=>{if(e.repeat==='Weekly'&&e.repeatEnd){let d=new Date(e.date+'T12:00'),end=new Date(e.repeatEnd+'T12:00'),skip=new Set(e.excludedDates||[]);while(d<=end){let ds=iso(d);if(!skip.has(ds))out.push({...e,date:ds});d.setDate(d.getDate()+7)}}else out.push(e)});return out}
function rec(person,all){let g=all.filter(e=>(e.person===person||e.person==='Both')&&e.result);return {w:g.filter(e=>e.result==='Win').length,l:g.filter(e=>e.result==='Loss').length,t:g.filter(e=>e.result==='Tie').length}}
function shortTeam(person){return person==='Richard'?'Mariners':'Giants'}
function opponent(e){if(!e)return '';let o=(e.opponent||'Opponent').replace(/^SSLL\s+(AA|Teeball Majors)\s+/i,'');return (e.homeAway==='Away'?'@ ':'vs ')+o}
function sports(ds){let all=sportEvents().sort((a,b)=>(a.date+(a.time||'99:99')).localeCompare(b.date+(b.time||'99:99')));let row=person=>{let r=rec(person,all),next=all.find(e=>e.date>=ds&&(e.person===person||e.person==='Both')),record=r.w+'-'+r.l+(r.t?'-'+r.t:'');return '<div class="score-team"><div class="score-team-id"><span class="score-logo" style="--team:'+personColor(person)+'">'+(person==='Richard'?'M':'G')+'</span><span><small>'+esc(person)+'</small><b>'+shortTeam(person)+'</b><em>'+record+'</em></span></div><div class="score-next">'+(next?'<small>NEXT GAME</small><b>'+esc(opponent(next))+'</b><span>'+fmtDate(next.date)+' · '+ft(next.time)+'</span>':'<small>NEXT GAME</small><b>Season complete</b><span>No upcoming game</span>')+'</div></div>'};return '<section class="card dash-extra dash-sports dash-scoreboard" data-dashboard-only="1" data-dashboard-tile="sports"><div class="score-head"><span>⚾ FAMILY BASEBALL</span><button data-extra-go="sports">Sports Hub ›</button></div><div class="score-teams">'+row('Richard')+row('Timothy')+'</div></section>'}
function wellness(ds){let mood=data.moodLog?.[ds],smoke=data.smokingLog?.[ds]||data.smokeLog?.[ds],period=data.periodLog?.[ds],bits=[];if(mood)bits.push('Mood logged');if(smoke)bits.push('Smoking logged');if(period)bits.push('Period logged');return '<section class="card dash-extra dash-wellness" data-dashboard-only="1" data-dashboard-tile="wellness"><div class="dash-card-kicker"><span>♡</span><b>WELLNESS</b></div><div class="card-head"><div><h2>Wellness</h2><div class="meta">Today’s check-ins</div></div><span class="pill">'+bits.length+' logged</span></div><div class="dash-extra-stat"><b>'+bits.length+'</b><span>wellness check-in'+(bits.length===1?'':'s')+' today</span></div><div class="meta dash-extra-note">'+(bits.length?esc(bits.join(' · ')):'Nothing logged yet today')+'</div><button class="dash-extra-link" data-extra-go="wellness">Open Wellness</button></section>'}
function debt(){let rows=data.debts||data.debtAccounts||[],current=rows.reduce((s,x)=>s+Number(x.balance??x.currentBalance??0),0),start=rows.reduce((s,x)=>s+Number(x.startingBalance??x.originalBalance??x.balance??0),0),paid=Math.max(0,start-current),pct=start?Math.min(100,Math.round(paid/start*100)):0;return '<section class="card dash-extra dash-debt" data-dashboard-only="1" data-dashboard-tile="debt-pay-down"><div class="dash-card-kicker"><span>💳</span><b>DEBT PAY DOWN</b></div><div class="card-head"><div><h2>Debt progress</h2><div class="meta">'+rows.length+' account'+(rows.length===1?'':'s')+' tracked</div></div><span class="pill">'+pct+'%</span></div><div class="dash-extra-stat"><b>$'+Math.round(current).toLocaleString()+'</b><span>remaining balance</span></div><div class="dash-progress"><i style="width:'+pct+'%"></i></div><button class="dash-extra-link" data-extra-go="debt">Open Debt</button></section>'}
const tiles=[{selector:'.dash-sports',render:()=>sports(vegasToday())},{selector:'.dash-wellness',render:()=>wellness(vegasToday())},{selector:'.dash-debt',render:debt}];
function removeDashboardOnly(){let r=root();if(!r)return;r.querySelectorAll('[data-dashboard-only="1"]').forEach(x=>x.remove())}
function reconcile(){let r=root();if(!r)return;let surface=syncSurface();if(surface!=='home'){removeDashboardOnly();return}let added=false;tiles.forEach(t=>{if(!r.querySelector(t.selector)){r.insertAdjacentHTML('beforeend',t.render());added=true}});if(added)document.dispatchEvent(new CustomEvent('family-dashboard-ready'))}
let timer;function schedule(){clearTimeout(timer);timer=setTimeout(reconcile,120)}
document.addEventListener('click',e=>{let b=e.target.closest?.('[data-extra-go]');if(b){e.preventDefault();e.stopPropagation();go(b.dataset.extraGo);setTimeout(reconcile,180);return}if(e.target.closest?.('[data-view],[data-action="more"],[data-sports-open],[data-debt-open]'))setTimeout(reconcile,180)});
document.addEventListener('family-dashboard-ready',reconcile);document.addEventListener('DOMContentLoaded',()=>{let r=root();if(r)new MutationObserver(schedule).observe(r,{childList:true});schedule()});
let lastSports='';setInterval(()=>{if(!homeMounted()){removeDashboardOnly();return}reconcile();let key=vegasToday()+'|'+(data.events||[]).map(e=>[e.id,e.result,e.teamScore,e.opponentScore].join(':')).join(',');if(key!==lastSports){lastSports=key;let r=root(),old=r.querySelector('.dash-sports');if(old){let temp=document.createElement('div');temp.innerHTML=sports(vegasToday());old.replaceWith(temp.firstElementChild);document.dispatchEvent(new CustomEvent('family-dashboard-ready'))}}},1500);
})();

