// Home dashboard editor — all visible Home tiles v213a
(function(){
const fixed=/running on empty|remember today|today.?s verse/i;
function R(){return document.querySelector('#dashboard')}
function isHome(){try{return (window.view||view)==='home'}catch(e){return false}}
function label(el){return (el.querySelector('h2')?.textContent||el.querySelector('h3')?.textContent||'').trim()}
function slug(s){return s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function motivation(r){return [...r.children].find(el=>fixed.test(el.textContent||''))}
function isFixed(el){return !el||el.classList.contains('dashboard-editbar')||el.classList.contains('attention-card')||fixed.test(el.textContent||'')}
function getTiles(r){let out=[];[...r.children].forEach(el=>{if(isFixed(el))return;if(!el.classList.contains('card'))return;let id=el.dataset.dashboardTile||'';if(!id){if(el.classList.contains('family-glance'))id='at-a-glance';else if(el.classList.contains('family-next'))id='up-next';else if(el.classList.contains('family-today'))id='today';else id=slug(label(el)||('tile-'+out.length))}if(!id)return;el.dataset.dashboardTile=id;out.push([id,el])});return out}
function savedOrder(pairs){data.settings=data.settings||{};let ids=pairs.map(x=>x[0]),saved=Array.isArray(data.settings.dashboardOrderAll)?data.settings.dashboardOrderAll:[];let o=saved.filter(x=>ids.includes(x));ids.forEach(x=>{if(!o.includes(x))o.push(x)});return o}
function ensureBar(){let r=R();if(!r)return;let bar=r.querySelector('.dashboard-editbar');if(!bar){bar=document.createElement('div');bar.className='dashboard-editbar';bar.innerHTML='<button type="button" class="mini secondary" data-dashboard-edit>↕ Edit dashboard</button>'}let mot=motivation(r);if(mot){if(mot.previousElementSibling!==bar)mot.insertAdjacentElement('beforebegin',bar)}else r.prepend(bar)}
function arrange(){if(!isHome())return;let r=R();if(!r)return;ensureBar();let pairs=getTiles(r),map=Object.fromEntries(pairs),o=savedOrder(pairs),anchor=r.querySelector('.attention-card');o.forEach(id=>{let el=map[id];if(!el)return;if(anchor){anchor.insertAdjacentElement('afterend',el);anchor=el}else r.appendChild(el)});ensureBar();if(r.classList.contains('dashboard-editing'))decorate()}
function decorate(){let r=R();if(!r)return;r.querySelectorAll('.dash-movers').forEach(x=>x.remove());if(!r.classList.contains('dashboard-editing'))return;let pairs=getTiles(r),o=savedOrder(pairs),map=Object.fromEntries(pairs);o.forEach((id,i)=>{let el=map[id];if(!el)return;let d=document.createElement('div');d.className='dash-movers';d.innerHTML='<span>Move</span><button type="button" data-dashboard-move="'+id+'" data-dir="-1" aria-label="Move '+id+' up" '+(i===0?'disabled':'')+'>↑</button><button type="button" data-dashboard-move="'+id+'" data-dir="1" aria-label="Move '+id+' down" '+(i===o.length-1?'disabled':'')+'>↓</button>';el.appendChild(d)})}
function toggle(){let r=R();if(!r)return;ensureBar();let bar=r.querySelector('.dashboard-editbar'),on=r.classList.toggle('dashboard-editing');bar.innerHTML=on?'<span class="meta">Reorder Home tiles</span><button type="button" class="mini" data-dashboard-done>Done</button>':'<button type="button" class="mini secondary" data-dashboard-edit>↕ Edit dashboard</button>';decorate()}
function move(id,dir){let r=R(),pairs=getTiles(r),map=Object.fromEntries(pairs),o=savedOrder(pairs),i=o.indexOf(id),j=i+Number(dir);if(i<0||j<0||j>=o.length)return;[o[i],o[j]]=[o[j],o[i]];data.settings.dashboardOrderAll=o;localSave();syncSave();let anchor=r.querySelector('.attention-card');o.forEach(k=>{let el=map[k];if(!el)return;if(anchor){anchor.insertAdjacentElement('afterend',el);anchor=el}else r.appendChild(el)});ensureBar();decorate()}
document.addEventListener('click',e=>{if(e.target.closest?.('[data-dashboard-edit],[data-dashboard-done]')){e.preventDefault();e.stopPropagation();toggle();return}let b=e.target.closest?.('[data-dashboard-move]');if(b){e.preventDefault();e.stopPropagation();move(b.dataset.dashboardMove,b.dataset.dir)}});
let timer;function schedule(){clearTimeout(timer);timer=setTimeout(()=>{if(isHome())arrange()},40)}document.addEventListener('DOMContentLoaded',()=>{let r=R();if(r)new MutationObserver(schedule).observe(r,{childList:true});schedule()});setInterval(()=>{if(isHome())arrange()},1200);
})();
