// Debt Pay Down — full page v187a
(function(){
function ensure(){data.debts=data.debts||[];data.debtPayments=data.debtPayments||[]}
function money(n){return '$'+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
function persist(){if(typeof save==='function')save();else localStorage.setItem('familyHubData',JSON.stringify(data))}
function markup(){ensure();let debts=[...data.debts].sort((a,b)=>(+a.balance||0)-(+b.balance||0)),bal=debts.reduce((a,d)=>a+(+d.balance||0),0),mins=debts.reduce((a,d)=>a+(+d.minimum||0),0);return '<section class="card full debt-page"><div class="card-head debt-top"><div><div class="eyebrow">MONEY</div><h2>Debt Pay Down</h2><div class="meta">Balances, payments & progress</div></div><button type="button" class="primary" id="addDebt">＋ Debt</button></div><div class="debt-stats"><div><span>Total remaining</span><strong>'+money(bal)+'</strong></div><div><span>Accounts</span><strong>'+debts.length+'</strong></div><div><span>Monthly minimums</span><strong>'+money(mins)+'</strong></div></div><div class="debt-list">'+(debts.length?debts.map(d=>{let start=+d.startingBalance||+d.balance||0,b=+d.balance||0,pct=start?Math.max(0,Math.min(100,(1-b/start)*100)):0;return '<div class="debt-row"><div class="debt-main"><div><b>'+d.name+'</b><div class="meta">'+(d.apr?d.apr+'% APR · ':'')+(d.minimum?'Minimum '+money(d.minimum):'No minimum entered')+'</div></div><strong>'+money(b)+'</strong></div><div class="debt-progress"><i style="width:'+pct+'%"></i></div><div class="debt-foot"><span>'+pct.toFixed(0)+'% paid down</span><div class="item-actions"><button type="button" class="mini debt-payment" data-id="'+d.id+'">Record payment</button><button type="button" class="mini edit-debt" data-id="'+d.id+'">Edit</button></div></div></div>'}).join(''):'<p class="muted">No debts added yet. Add an account to start tracking your pay down.</p>')+'</div></section>'}
function page(){ensure();$('#modal')?.close();let root=$('#dashboard');if(root)root.innerHTML=markup();document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));document.querySelector('nav [data-action="more"]')?.classList.add('active');let h=$('#dailyEncouragement');if(h)h.innerHTML=''}
function inject(){let menu=document.querySelector('.more-menu');if(!menu||menu.querySelector('[data-debt-open]'))return;let moneyGroup=[...menu.querySelectorAll('.more-group')].find(g=>g.querySelector('.eyebrow')?.textContent.trim()==='MONEY'),grid=moneyGroup?.querySelector('.more-grid');if(!grid)return;let b=document.createElement('button');b.type='button';b.className='more-destination';b.dataset.debtOpen='1';b.innerHTML='<span class="more-icon">💳</span><span><b>Debt Pay Down</b><small>Balances, payments, progress</small></span><i>›</i>';grid.appendChild(b);let future=menu.querySelector('.more-future');if(future)future.remove()}
function edit(id){ensure();let d=data.debts.find(x=>x.id==id),fresh=!d;if(!d)d={id:Date.now(),name:'',balance:'',startingBalance:'',apr:'',minimum:''};$('#modalTitle').textContent=fresh?'Add debt':'Edit debt';$('#modalBody').innerHTML='<div class="form-grid"><label class="field full">Account name<input id="debtName" value="'+(d.name||'')+'" placeholder="Credit card, car loan..."></label><label class="field">Current balance<input id="debtBalance" type="number" min="0" step=".01" value="'+(d.balance||'')+'"></label><label class="field">Starting balance<input id="debtStart" type="number" min="0" step=".01" value="'+(d.startingBalance||d.balance||'')+'"></label><label class="field">APR %<input id="debtApr" type="number" min="0" step=".01" value="'+(d.apr||'')+'"></label><label class="field">Minimum payment<input id="debtMin" type="number" min="0" step=".01" value="'+(d.minimum||'')+'"></label></div><div class="modal-actions">'+(fresh?'<button type="button" class="mini" id="debtCancel">Cancel</button>':'<button type="button" class="danger" id="deleteDebt">Delete</button>')+'<button type="button" class="primary" id="saveDebt">Save</button></div>';$('#modal').showModal();$('#saveDebt').onclick=()=>{d.name=$('#debtName').value.trim();d.balance=$('#debtBalance').value;d.startingBalance=$('#debtStart').value||d.startingBalance||d.balance;d.apr=$('#debtApr').value;d.minimum=$('#debtMin').value;if(!d.name)return alert('Enter an account name.');if(fresh)data.debts.push(d);persist();page()};$('#debtCancel')&&($('#debtCancel').onclick=page);$('#deleteDebt')&&($('#deleteDebt').onclick=()=>{if(confirm('Delete this debt?')){data.debts=data.debts.filter(x=>x.id!=d.id);persist();page()}})}
function payment(id){let d=data.debts.find(x=>x.id==id);if(!d)return;$('#modalTitle').textContent='Record payment';$('#modalBody').innerHTML='<p class="meta">'+d.name+' · current balance '+money(d.balance)+'</p><label class="field">Payment amount<input id="debtPayAmount" type="number" min="0" step=".01" placeholder="0.00"></label><div class="modal-actions"><button type="button" class="mini" id="debtCancel">Cancel</button><button type="button" class="primary" id="saveDebtPayment">Apply payment</button></div>';$('#modal').showModal();$('#debtCancel').onclick=page;$('#saveDebtPayment').onclick=()=>{let amt=+$('#debtPayAmount').value;if(!(amt>0))return;d.balance=Math.max(0,(+d.balance||0)-amt).toFixed(2);data.debtPayments.push({id:Date.now(),debtId:d.id,amount:amt,date:vegasToday()});persist();page()}}
document.addEventListener('click',e=>{if(e.target.closest?.('[data-action="more"]'))setTimeout(inject,0);if(e.target.closest?.('[data-debt-open]'))page();if(e.target.closest?.('#addDebt'))edit();let ed=e.target.closest?.('.edit-debt');if(ed)edit(+ed.dataset.id);let pay=e.target.closest?.('.debt-payment');if(pay)payment(+pay.dataset.id)});
})();