// Presentation only: no family or financial data mutations.
(function(){
 'use strict';const $=s=>document.querySelector(s);let expanded=false;
 const symbols={calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 11h18"/>',tasks:'<rect x="3" y="3" width="18" height="18" rx="4"/><path d="m7 12 3 3 7-7"/>',habits:'<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9Z"/>',shop:'<path d="M3 3h2l3 12h11l2-8H6M9 20h.01M18 20h.01"/>',activity:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',meals:'<path d="M5 3v6m3-6v6M3 3v4a3 3 0 0 0 6 0V3M6 10v11M18 3c-4 3-4 8 0 9v9M18 3v9"/>',more:'<circle cx="12" cy="12" r="9"/><path d="M15 8h-4a2 2 0 0 0 0 4h2a2 2 0 0 1 0 4H9m3-10v12"/>',settings:'<circle cx="12" cy="12" r="4"/><path d="M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2"/>',sports:'<circle cx="12" cy="12" r="9"/><path d="M6 5c6 3 6 11 0 14M18 5c-6 3-6 11 0 14"/>',debt:'<rect x="2" y="5" width="20" height="14" rx="3"/><path d="M2 10h20M6 15h4"/>',meds:'<path d="m4 13 9-9a5 5 0 0 1 7 7l-9 9a5 5 0 0 1-7-7Zm4-4 7 7"/>'};
 function symbol(key){return '<svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">'+(symbols[key]||symbols.more)+'</svg>'}
 Object.assign(symbols,{home:'<path d="m3 11 9-8 9 8M5 10v11h5v-7h4v7h5V10"/>',today:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',add:'<path d="M12 5v14M5 12h14"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>'});
 function navIcons(){document.querySelectorAll('.primary-nav button').forEach(b=>{if(b.querySelector('.hv-nav-icon'))return;let first=b.firstChild;if(first?.nodeType!==3)return;let key=b.dataset.view||b.dataset.action;if(key==='money')key='more';else if(key==='more')key='menu';let icon=document.createElement('span');icon.className='hv-nav-icon';icon.setAttribute('aria-hidden','true');icon.innerHTML=symbol(key);first.replaceWith(icon)})}
 function modalIcons(){document.querySelectorAll('#modal .more-destination').forEach(b=>{let icon=b.querySelector('.more-icon');if(!icon||icon.dataset.hvSymbol)return;let key=b.dataset.moreView||(b.hasAttribute('data-sports-open')?'sports':b.hasAttribute('data-debt-open')?'debt':b.hasAttribute('data-meds-open')?'meds':'more');icon.dataset.hvSymbol=key;icon.setAttribute('aria-hidden','true');icon.innerHTML=symbol(key)})}
 function apply(){let root=$('#dashboard');if(!root)return;navIcons();let home=!!root.querySelector('.family-glance'),today=!!root.querySelector('.today-plan');$('#app').dataset.visualSurface=home?'home':today?'today':'other';
  if(home){let list=$('.family-next-list'),rows=[...list.querySelectorAll('.family-next-row')];rows.forEach((r,i)=>r.hidden=!expanded&&i>=3);let more=$('#hvMoreEvents');if(rows.length>3){if(!more){more=document.createElement('button');more.type='button';more.id='hvMoreEvents';more.className='hv-text-button';list.after(more);more.onclick=()=>{expanded=!expanded;apply()}}let text=expanded?'Show fewer events':'Show all '+rows.length+' upcoming events';if(more.textContent!==text)more.textContent=text;more.setAttribute('aria-expanded',String(expanded))}
   const icons={calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 11h18"/>',tasks:'<rect x="3" y="3" width="18" height="18" rx="4"/><path d="m7 12 3 3 7-7"/>',habits:'<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9Z"/>',shop:'<path d="M3 3h2l3 12h11l2-8H6M9 20h.01M18 20h.01"/>'};root.querySelectorAll('.family-glance-grid [data-dash-go]').forEach(b=>{let icon=b.querySelector('span');if(icon.dataset.hvIcon)return;icon.dataset.hvIcon='1';icon.setAttribute('aria-hidden','true');icon.innerHTML='<svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">'+icons[b.dataset.dashGo]+'</svg>'});
   root.querySelectorAll('.weather').forEach(w=>{if(w.querySelector('details')||w.children.length<5)return;let details=document.createElement('details');details.className='hv-weather-details';let summary=document.createElement('summary');summary.textContent='Forecast and wind';details.append(summary);[...w.children].slice(4).forEach(x=>details.append(x));w.append(details)});
   root.querySelectorAll('.week').forEach(week=>{week.setAttribute('aria-label','Seven-day family schedule');if(!week.nextElementSibling?.classList.contains('hv-week-hint')){let hint=document.createElement('p');hint.className='hv-week-hint meta';hint.textContent='Swipe across to see the week, or tap a day for details.';week.after(hint)}});
   root.querySelectorAll('.day .tag').forEach(tag=>{let text=tag.textContent,next=text.replace(/^(\d{1,2}:\d{2})(?=\s*·)/,t=>window.familyHubTime.format(t));if(next!==text)tag.textContent=next});
  }
  root.querySelectorAll('.home-task-row .task-check').forEach(input=>{let name=input.closest('.home-task-row').querySelector('div>b')?.textContent;if(name&&!input.hasAttribute('aria-label'))input.setAttribute('aria-label','Complete '+name)});
  if(today&&!$('#hvTaskGrouping')){let section=$('.today-plan-section:last-child'),label=document.createElement('label');label.className='hv-setting';label.innerHTML='Group tasks by <select id="hvTaskGrouping"><option value="category">Category</option><option value="person">Person</option></select>';section.querySelector('h3').after(label);let select=label.querySelector('select');select.value=localStorage.getItem('familyHubTodayGrouping')||'category';select.onchange=()=>{localStorage.setItem('familyHubTodayGrouping',select.value);window.hubExperience.refresh()}}
  let settings=[...root.querySelectorAll('h2')].find(x=>x.textContent==='App & Sync');if(settings&&!$('#hvTimeMode')){let label=document.createElement('label');label.className='hv-setting';label.innerHTML='Time display on this device <select id="hvTimeMode"><option value="12">12-hour · 5:30 PM</option><option value="24">24-hour · 17:30</option></select>';settings.closest('.card').append(label);let select=label.querySelector('select');select.value=window.familyHubTime.mode();select.onchange=()=>{localStorage.setItem('familyHubTimeMode',select.value);window.hubExperience.refresh()}}
 }
 const previous=window.render;window.render=function(){let result=previous.apply(this,arguments);apply();return result};document.addEventListener('family-dashboard-ready',apply);window.addEventListener('familyHub:syncStatus',apply);window.addEventListener('budget2:render',apply);
 let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;queueMicrotask(()=>{queued=false;window.hubExperience?.settle();apply()})}).observe($('#dashboard'),{childList:true,subtree:true});apply();window.familyHubVisual={apply};
 new MutationObserver(modalIcons).observe($('#modalBody'),{childList:true,subtree:true});modalIcons();
 new MutationObserver(navIcons).observe($('.primary-nav'),{childList:true});navIcons();
})();

