// Explicit bill/debt links. Required amounts and planned budget targets stay distinct.
(function(){
 'use strict';const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function link(kind,item){let cats=data.budget?.categories||[];$('#modalTitle').textContent='Link '+item.name+' to budget';$('#modalBody').innerHTML='<p>Required '+(kind==='debt'?'minimum':'bill')+': $'+Number(kind==='debt'?item.minimum:item.amount||0)+'. A budget target may include extra funding. Linking does not change either amount.</p><label class="field">Budget category<select id="mlCategory"><option value="">No link</option>'+cats.filter(c=>!c.archived).map(c=>'<option value="'+esc(c.id)+'" '+(String(item.budgetCategoryId)===String(c.id)?'selected':'')+'>'+esc(c.name)+' · planned $'+Number(c.expectedMonthly||0)+'</option>').join('')+'</select></label><button type="button" id="mlSave">Save link</button>';$('#modal').showModal();$('#mlSave').onclick=()=>{let selected=$('#mlCategory').value;if(selected&&data[kind==='debt'?'debts':'payments'].some(x=>x!==item&&String(x.budgetCategoryId)===selected))return alert('That category is already linked to another '+kind+'.');item.budgetCategoryId=selected;save();$('#modal').close();if($('.budget2-page'))window.moneyWorkspace.refresh();else if(kind==='debt')window.openDebtHub();else render()}}
 function payment(debt){let c=(data.budget?.categories||[]).find(c=>String(c.id)===String(debt.budgetCategoryId));if(!c)return alert('Review the budget link first.');if(c.creditAccountId){window.openBudgetTransfer();$('#tfTo').value=c.creditAccountId;return}let accounts=(data.budget.accounts||[]).filter(a=>!window.creditCardBudget.credit(a));$('#modalTitle').textContent='Record '+debt.name+' payment';$('#modalBody').innerHTML='<p>The full payment leaves the cash account and budget bucket. Only the principal portion reduces the debt balance.</p><label class="field">Cash account<select id="mlAccount">'+accounts.map(a=>'<option value="'+esc(a.id)+'">'+esc(a.name)+'</option>').join('')+'</select></label><label class="field">Total payment<input type="number" step=".01" id="mlTotal"></label><label class="field">Principal portion<input type="number" step=".01" id="mlPrincipal"></label><button type="button" id="mlPay">Save payment</button>';$('#modal').showModal();$('#mlPay').onclick=()=>{let total=Number($('#mlTotal').value),principal=Number($('#mlPrincipal').value);if(!Number.isFinite(principal)||principal<0||principal>total||principal>Number(debt.balance))return alert('Enter a principal portion within the payment and debt balance.');let x={id:crypto.randomUUID(),date:vegasToday(),type:'expense',amount:total,accountId:$('#mlAccount').value,categoryId:c.id,merchant:debt.name+' payment',linkedDebtId:debt.id,principal,createdAt:new Date().toISOString()};let error=window.creditCardBudget.prepare(x);if(error)return alert(error);if(Number(accounts.find(a=>String(a.id)===x.accountId)?.balance)<total)return alert('The paying account does not have enough cash.');data.budget.transactions.push(x);window.creditCardBudget.effect(x,1);debt.balance=Math.round((Number(debt.balance)-principal)*100)/100;data.debtPayments.push({id:crypto.randomUUID(),debtId:debt.id,amount:total,principal,date:x.date,transactionId:x.id});save();$('#modal').close();window.openDebtHub()}}
 function enhance(){if(typeof data==='undefined')return;document.querySelectorAll('.edit-payment,.edit-debt').forEach(edit=>{let row=edit.closest('.item,.debt-row');if(!row||row.querySelector('[data-budget-link]'))return;let kind=edit.matches('.edit-debt')?'debt':'bill',item=(kind==='debt'?data.debts:data.payments).find(x=>String(x.id)===edit.dataset.id);if(!item)return;let c=(data.budget?.categories||[]).find(c=>String(c.id)===String(item.budgetCategoryId)),button=document.createElement('button');button.type='button';button.className='mini';button.dataset.budgetLink=kind;button.textContent=c?'Budget: '+c.name:'Link budget';button.onclick=()=>link(kind,item);edit.parentElement.append(button);if(c){let label=document.createElement('p');label.className='meta';label.textContent='Required '+(kind==='debt'?'minimum':'bill')+' $'+Number(kind==='debt'?item.minimum:item.amount||0)+' · Budget planned $'+Number(c.expectedMonthly||0);row.append(label)}})}
 document.addEventListener('click',e=>{let pay=e.target.closest?.('.debt-payment');if(!pay)return;let debt=(data.debts||[]).find(x=>String(x.id)===pay.dataset.id);if(debt?.budgetCategoryId){e.preventDefault();e.stopImmediatePropagation();payment(debt)}},true);
 let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(enhance,40)}).observe($('#dashboard'),{childList:true,subtree:true});
})();
