// Reviewed CSV / JSON imports. No remote parser and no automatic commits.
(function(root){
 'use strict';
 function csv(text){let rows=[],row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){let c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=''}else cell+=c}if(quoted)throw new Error('Unclosed CSV quote.');row.push(cell);if(row.some(x=>x.trim()))rows.push(row);if(rows.length<2)throw new Error('Include column headings and at least one row.');let headers=rows.shift().map(x=>x.replace(/^\uFEFF/,'').trim().toLowerCase());return rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]||''])))}
 function numeric(value){if(typeof value==='number')return value;let s=String(value??'').trim();if(!s)return NaN;let negative=/^\(.*\)$/.test(s);s=s.replace(/[,$()]/g,'').replace(/^\$/,'');return Number(s)*(negative?-1:1)}
 function day(value){let s=String(value||'').trim();if(/^\d{1,2}\/\d{1,2}\/\d{4}$/.test(s)){let [m,d,y]=s.split('/');s=y+'-'+m.padStart(2,'0')+'-'+d.padStart(2,'0')}if(!/^\d{4}-\d{2}-\d{2}$/.test(s))throw new Error('Use YYYY-MM-DD or MM/DD/YYYY dates.');let d=new Date(s+'T12:00:00Z');if(!Number.isFinite(d.getTime())||d.toISOString().slice(0,10)!==s)throw new Error('Invalid date '+s);return s}
 function parse(text){text=text.trim().replace(/^```(?:json|csv)?\s*\n/i,'').replace(/\n```\s*$/,'');let raw=text.startsWith('[')||text.startsWith('{')?JSON.parse(text):csv(text);if(!Array.isArray(raw))raw=raw.transactions;if(!Array.isArray(raw))throw new Error('JSON must be a transaction array or {transactions:[...]}.');if(raw.length>2000)throw new Error('Review at most 2,000 rows at once.');return raw.map((r,i)=>{let lower=Object.fromEntries(Object.entries(r).map(([k,v])=>[k.toLowerCase(),v])),amount=numeric(lower.amount),type=String(lower.type||'expense').toLowerCase();if(lower.debit!==undefined||lower.credit!==undefined){let debit=numeric(lower.debit)||0,credit=numeric(lower.credit)||0;if(debit&&credit)throw new Error('Row '+(i+1)+': debit and credit both present.');amount=debit||credit;type=credit?'income':'expense'}if(!Number.isFinite(amount)||amount<=0)throw new Error('Row '+(i+1)+': use a positive Amount and an explicit expense/income type, or separate Debit/Credit columns.');if(!['expense','income','transfer'].includes(type))throw new Error('Row '+(i+1)+': unsupported type.');return {date:day(lower.date),amount:Math.round(amount*100)/100,merchant:String(lower.merchant||lower.description||lower.payee||'').trim(),type,account:String(lower.account||lower.accountid||''),category:String(lower.category||lower.categoryid||''),to:String(lower.to||lower.transferaccountid||'')}})}
 function fingerprint(x){return [x.type,x.date,Math.round(Number(x.amount)*100),String(x.accountId),String(x.transferAccountId||''),String(x.categoryId||''),String(x.merchant||'').trim().toLowerCase()].join('|')}
 const api={csv,parse,fingerprint};if(typeof module!=='undefined'&&module.exports){module.exports=api;return}root.moneyImport=api;
 const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const options=(rows,selected)=>'<option value="">Choose…</option>'+rows.map(x=>'<option value="'+esc(x.id)+'" '+(String(x.id)===String(selected)?'selected':'')+'>'+esc(x.name)+'</option>').join('');
 function resolve(rows,value){return rows.find(x=>String(x.id)===value||String(x.name).toLowerCase()===value.toLowerCase())?.id||''}
 api.open=function(){let b=data.budget;$('#modalTitle').textContent='Import transactions';$('#modalBody').innerHTML='<p>Paste CSV or a JSON transaction block from ChatGPT. Everything stays on this device until you review and save. Use Date, Amount, Merchant, Type, Account and Category columns. Amounts must be positive; Type is expense, income or transfer. Debit/Credit columns are also supported.</p><label class="field">CSV file<input id="miFile" type="file" accept=".csv,text/csv"></label><label class="field">CSV or JSON<textarea id="miText" rows="7" placeholder="Date,Amount,Merchant,Type,Account,Category"></textarea></label><p id="miError" aria-live="polite"></p><button type="button" id="miPreview">Preview import</button><div id="miRows"></div>';$('#modal').showModal();$('#miFile').onchange=async e=>{$('#miText').value=await e.target.files[0]?.text()||''};$('#miPreview').onclick=()=>{try{let parsed=parse($('#miText').value);$('#miError').textContent='';preview(parsed,b)}catch(e){$('#miError').textContent=e.message}}};
 function preview(parsed,b){let seen=new Set(b.transactions.map(fingerprint)),cats=b.categories.filter(c=>!c.archived&&!c.creditAccountId),accts=b.accounts,rows=parsed.map(r=>{let x={...r,accountId:String(resolve(accts,r.account)),categoryId:String(resolve(cats,r.category)||b.merchantRules?.[r.merchant.trim().toLowerCase()]||''),transferAccountId:String(resolve(accts,r.to))};let key=fingerprint(x),duplicate=seen.has(key);seen.add(key);return {...x,duplicate}});$('#miRows').innerHTML='<p>'+rows.length+' rows. Possible duplicates are unchecked. Confirm each account, bucket, type and date. Importing updates current account balances; do not import transactions already included in a starting balance.</p>'+rows.map((r,i)=>'<fieldset data-import-row="'+i+'"><legend><label><input type="checkbox" data-include '+(!r.duplicate?'checked':'')+'> '+esc(r.date)+' · '+esc(r.merchant)+' · $'+r.amount+(r.duplicate?' · Possible duplicate':'')+'</label></legend><label class="field">Account<select data-account>'+options(accts,r.accountId)+'</select></label>'+(r.type==='expense'?'<label class="field">Bucket<select data-category>'+options(cats,r.categoryId)+'</select></label>':r.type==='transfer'?'<label class="field">To account<select data-to>'+options(accts,r.transferAccountId)+'</select></label>':'')+'</fieldset>').join('')+'<label><input type="checkbox" id="miRemember"> Remember selected merchant categories for future imports</label><label><input type="checkbox" id="miBalances"> These rows are not already included in my recorded balances</label><p id="miCommitError" aria-live="polite"></p><button type="button" class="primary" id="miCommit">Save selected transactions</button>';
  $('#miCommit').onclick=()=>{if(!$('#miBalances').checked){$('#miCommitError').textContent='Confirm the starting-balance check before saving.';return}let selected=rows.map((r,i)=>{let field=$('[data-import-row="'+i+'"]');if(!field.querySelector('[data-include]').checked)return null;return {id:crypto.randomUUID(),type:r.type,date:r.date,merchant:r.merchant,amount:r.amount,accountId:field.querySelector('[data-account]').value,categoryId:field.querySelector('[data-category]')?.value,transferAccountId:field.querySelector('[data-to]')?.value,createdAt:new Date().toISOString(),importBatch:'pending'}}).filter(Boolean);if(!selected.length)return;
   let original=data,trial=JSON.parse(JSON.stringify(data)),error='';try{data=trial;for(let x of selected){if(!x.merchant){error='Every row needs a merchant or description.';break}error=window.creditCardBudget.prepare(x);if(error)break;trial.budget.transactions.push(x);window.creditCardBudget.effect(x,1)}}finally{data=original}if(error){$('#miCommitError').textContent=error+' Nothing was saved.';return}
   let remember=$('#miRemember').checked,batch=crypto.randomUUID();if(remember){b.merchantRules=b.merchantRules||{};selected.filter(x=>x.type==='expense').forEach(x=>b.merchantRules[x.merchant.trim().toLowerCase()]=x.categoryId)}selected.forEach(x=>{x.importBatch=batch;b.transactions.push(x);window.creditCardBudget.effect(x,1)});b.importHistory=b.importHistory||[];b.importHistory.push({id:batch,createdAt:new Date().toISOString(),count:selected.length});save();$('#modal').close();window.moneyWorkspace.refresh()
  }
 }
})(typeof window==='undefined'?{}:window);
