// Monthly zero-based budget v271a
(function(){
 var months=['2026-09','2026-10','2026-11'],labels={'2026-09':'September 2026','2026-10':'October 2026','2026-11':'November 2026'};
 var defaults=[['Bills',['Rent','Water','Electricity','Gas']],['Everyday',['Groceries','Dining Out','Kids','Household','Medical','Fun / Personal','Miscellaneous']],['Debt',['Student Loan Payment','Extra Student Loan Paydown']],['Savings',['Savings']],['Leftover',['Leftover Budget']]];
 function money(n){return '$'+Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2})}
 function ensure(){if(typeof data==='undefined')return false;data.budget=data.budget||{};data.budget.monthly=data.budget.monthly||{};data.budget.categories=data.budget.categories||[];if(!data.budget.categories.length){defaults.forEach(function(g){g[1].forEach(function(n){data.budget.categories.push({id:(g[0]+'-'+n).toLowerCase().replace(/[^a-z0-9]+/g,'-'),group:g[0],name:n})})});(data.payments||[]).forEach(function(p){if(!data.budget.categories.some(function(x){return x.name.toLowerCase()===String(p.name||'').toLowerCase()}))data.budget.categories.push({id:'bill-'+p.id,group:'Bills',name:p.name})})}months.forEach(function(m){data.budget.monthly[m]=data.budget.monthly[m]||{assignments:{}}});data.budget.activeMonth=data.budget.activeMonth||months[0];return true}
 function saveIt(){if(typeof save==='function')save();else localStorage.setItem('familyHubData',JSON.stringify(data))}
 function activity(cat,month){return (data.budgetExpenses||[]).filter(function(x){return String(x.date||'').slice(0,7)===month&&String(x.category||'').toLowerCase()===String(cat.name).toLowerCase()}).reduce(function(s,x){return s+(Number(x.amount)||0)},0)}
 function priorAvailable(cat,month){var idx=months.indexOf(month),sum=0;for(var i=0;i<idx;i++){var mm=months[i],a=Number(data.budget.monthly[mm].assignments[cat.id])||0;sum+=a-activity(cat,mm)}return sum}
 function assigned(cat,m){return Number(data.budget.monthly[m].assignments[cat.id])||0} function available(cat,m){return priorAvailable(cat,m)+assigned(cat,m)-activity(cat,m)}
 function totalCash(){return (data.budget.accounts||[]).filter(function(a){return a.type!=='Credit'}).reduce(function(s,a){return s+(Number(a.balance)||0)},0)}
 function totalAssigned(){var s=0;months.forEach(function(m){Object.keys(data.budget.monthly[m].assignments).forEach(function(k){s+=Number(data.budget.monthly[m].assignments[k])||0})});return s} function moveFrom(id,m){var cats=data.budget.categories,from=cats.find(function(c){return c.id===id});if(!from)return;var max=available(from,m);if(max<=0)return alert('There is no available money in '+from.name+' to move.');var amt=Number(prompt('Move how much from '+from.name+'?\nAvailable: '+money(max),max));if(!isFinite(amt)||amt<=0||amt>max)return alert('Enter an amount no greater than the available balance.');var opts=cats.filter(function(c){return c.id!==id}).map(function(c,i){return (i+1)+'. '+c.name}).join('\n'),dest=cats.filter(function(c){return c.id!==id}),to=prompt('Move '+money(amt)+' from '+from.name+' TO:\n\n0. Ready to Assign\n'+opts);if(to===null)return;var n=parseInt(to,10),fa=assigned(from,m);if(amt>fa)return alert('For now, only money assigned this month can be moved. Rolled-over money movement comes with the rollover step.');data.budget.monthly[m].assignments[from.id]=fa-amt;if(n!==0){var target=dest[n-1];if(!target)return alert('Choose a category number or 0.');data.budget.monthly[m].assignments[target.id]=assigned(target,m)+amt}saveIt();render();window.dispatchEvent(new Event('budgetAccounts:render'))}
 function render(){var page=document.querySelector('.budget2-page');if(!page||!ensure())return;page.querySelectorAll('.mb-wrap').forEach(function(x){x.remove()});var m=data.budget.activeMonth;if(months.indexOf(m)<0)m=months[0];var idx=months.indexOf(m),ready=totalCash()-totalAssigned(),monthAssigned=Object.keys(data.budget.monthly[m].assignments||{}).reduce(function(s,k){return s+(Number(data.budget.monthly[m].assignments[k])||0)},0),box=document.createElement('div');box.className='mb-wrap';var groups=defaults.map(function(x){return x[0]});var rows=groups.map(function(g){var cats=data.budget.categories.filter(function(x){return x.group===g});if(!cats.length)return '';var body=cats.map(function(cat){var a=assigned(cat,m),act=activity(cat,m),avail=priorAvailable(cat,m)+a-act;return '<div class="mb-row" data-cat="'+cat.id+'"><span class="mb-cat">'+cat.name+'</span><button class="mb-assigned" data-assign="'+cat.id+'">'+money(a)+'</button><span>'+money(act?0-act:0)+'</span><button class="mb-available '+(avail<0?'negative':'')+'" data-movefrom="'+cat.id+'">'+money(avail)+'</button></div>'}).join('');return '<section class="mb-group"><div class="mb-grouphead"><b>⌄ '+g+'</b><span></span><span></span><b></b></div>'+body+'</section>'}).join('');box.innerHTML='<div class="mb-monthbar"><button id="mbPrev" '+(idx===0?'disabled':'')+'>‹</button><div><b>'+labels[m]+'</b><small>Give every dollar a job</small></div><button id="mbNext" '+(idx===months.length-1?'disabled':'')+'>›</button><div class="mb-ready"><small>ASSIGNED THIS MONTH</small><strong>'+money(monthAssigned)+'</strong></div></div><div class="mb-table"><div class="mb-columns"><b>CATEGORY</b><b>ASSIGNED</b><b>ACTIVITY</b><b>AVAILABLE</b></div>'+rows+'</div>';var acc=page.querySelector('.bacc-wrap'),head=page.querySelector('.budget2-head');if(acc)acc.parentNode.insertBefore(box,acc.nextSibling);else if(head)head.parentNode.insertBefore(box,head.nextSibling);else page.prepend(box);box.querySelector('#mbPrev').onclick=function(e){e.preventDefault();e.stopPropagation();if(idx<=0)return;data.budget.activeMonth=months[idx-1];saveIt();render()};box.querySelector('#mbNext').onclick=function(e){e.preventDefault();e.stopPropagation();if(idx>=months.length-1)return;data.budget.activeMonth=months[idx+1];saveIt();render()};box.querySelectorAll('[data-assign]').forEach(function(b){b.onclick=function(){editAssign(b.dataset.assign,m)}});box.querySelectorAll('[data-movefrom]').forEach(function(b){b.onclick=function(e){e.preventDefault();e.stopPropagation();moveFrom(b.dataset.movefrom,m)}})}
 function editAssign(id,m){var cat=data.budget.categories.find(function(x){return x.id===id}),cur=assigned(cat,m),v=prompt('Assign money to '+cat.name+' for '+labels[m]+':',cur);if(v===null)return;v=Number(v);if(!isFinite(v)||v<0)return alert('Enter a valid amount.');data.budget.monthly[m].assignments[id]=v;saveIt();render();window.dispatchEvent(new Event('budgetAccounts:render'))}
 document.addEventListener('click',function(e){if(e.target.closest&&e.target.closest('[data-action="money"]')){setTimeout(render,50);setTimeout(render,180)}});
 window.addEventListener('budget2:render',function(){setTimeout(render,60)});
})();