// Notifications 1.1 — v196a
(function(){
function cfg(){data.settings=data.settings||{};data.settings.notifications=data.settings.notifications||{enabled:false};return data.settings.notifications}
function supported(){return 'Notification' in window&&'serviceWorker' in navigator}
function statusText(){if(!supported())return 'Not supported on this browser';if(Notification.permission==='denied')return 'Blocked in browser settings';if(Notification.permission==='granted')return cfg().enabled?'On for this device':'Permission granted · notifications off';return 'Off · permission not requested'}
function controls(){let c=cfg();return '<div class="notification-settings"><div class="notification-setting-row"><span><b>🔔 Device notifications</b><small>'+statusText()+'</small></span><button type="button" class="mini" data-notification-toggle>'+(c.enabled?'Turn off':'Turn on')+'</button></div><div class="meta notification-note">Notifications use the reminder timing above. They can alert while Family Hub is open or active; true background push while the app is fully closed will require the next server-backed notification step.</div><button type="button" class="mini secondary" data-notification-test '+(!c.enabled||Notification.permission!=='granted'?'disabled':'')+'>Send test notification</button></div>'}
function inject(){if((window.view||view)!=='settings')return;let card=document.querySelector('.reminder-settings-card');if(!card||card.querySelector('.notification-settings'))return;card.insertAdjacentHTML('beforeend',controls())}
async function show(title,body,tag){if(!supported()||Notification.permission!=='granted')return;try{let reg=await navigator.serviceWorker.ready;await reg.showNotification(title,{body,tag:tag||'family-hub',renotify:false,data:{url:'./'}})}catch(e){try{new Notification(title,{body,tag:tag||'family-hub'})}catch(_){}}}
async function toggle(){let c=cfg();if(c.enabled){c.enabled=false;save();render();return}if(!supported()){alert('Notifications are not supported by this browser.');return}let p=Notification.permission;if(p==='default')p=await Notification.requestPermission();if(p==='granted'){c.enabled=true;save();render();setTimeout(()=>show('Family Hub notifications are on','You’ll get alerts based on your reminder settings.','family-hub-enabled'),250)}else{c.enabled=false;save();render()}}
function key(x){return [x.level,x.title,x.detail].join('|')}
async function check(){let c=cfg();if(!c.enabled||!supported()||Notification.permission!=='granted'||typeof familyAttention!=='function')return;let day=typeof vegasToday==='function'?vegasToday():new Date().toISOString().slice(0,10),storeKey='fh-notified-'+day,seen=[];try{seen=JSON.parse(localStorage.getItem(storeKey)||'[]')}catch(e){}let items=familyAttention(),fresh=items.filter(x=>!seen.includes(key(x)));if(!fresh.length)return;let x=fresh[0],extra=fresh.length>1?' · '+(fresh.length-1)+' more':'';await show(x.icon+' '+x.title,x.detail+extra,'family-hub-'+btoa(unescape(encodeURIComponent(key(x)))).slice(0,24));localStorage.setItem(storeKey,JSON.stringify([...seen,...fresh.map(key)]))}
document.addEventListener('click',e=>{if(e.target.closest?.('[data-notification-toggle]'))toggle();if(e.target.closest?.('[data-notification-test]'))show('Family Hub test','Notifications are working on this device.','family-hub-test')});let old=window.render;if(typeof old==='function'){window.render=function(){let r=old.apply(this,arguments);setTimeout(inject,0);return r}}else setInterval(inject,500);setInterval(check,60000);setTimeout(()=>{inject();check()},1500);
})();
