// Reminders 1.0 — grouped task attention v201a
(function(){
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function cfg(){data.settings=data.settings||{};data.settings.reminders=data.settings.reminders||{tasks:true,chores:true,payments:true,school:true,sports:true,paymentDays:1,schoolDays:1,sportsMinutes:120};return data.settings.reminders}
function add(ds,n){let d=new Date(ds+'T12:00');d.setDate(d.getDate()+n);return iso(d)}
function fmtTime(t){if(!t)return '';let [h,m]=t.split(':').map(Number),ap=h>=12?'PM':'AM';h=h%12||12;return h+(m?':'+String(m).padStart(2,'0'):'')+' '+ap}
function minutes(t){if(!t)return null;let [h,m]=t.split(':').map(Number);return h*60+(m||0)}
function nowMinutes(){let p=new Intl.DateTimeFormat('en-US',{timeZone:'America/Los_Angeles',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date()),o=Object.fromEntries(p.map(x=>[x.type,x.value]));return (+o.hour%24)*60+(+o.minute||0)}
window.familyAttention=function(){let c=cfg(),today=vegasToday(),items=[],overdue=[],todayTasks=[],chores=[];if(c.tasks||c.chores)(data.tasks||[]).forEach(t=>{if(t.taskMode==='cycle'){if(typeof taskDueToday==='function'&&taskDueToday(t)){if(t.category==='Work'){if(c.tasks)todayTasks.push(t)}else if(c.chores)chores.push(t)}return}if(!c.tasks||t.done)return;if(t.due&&t.due<today)overdue.push(t);else if(t.due===today)todayTasks.push(t)});if(overdue.length)items.push({level:'urgent',icon:'⚠️',title:overdue.length+' overdue task'+(overdue.length===1?'':'s'),detail:'Open Tasks to review',go:'tasks'});if(todayTasks.length)items.push({level:'today',icon:'✅',title:todayTasks.length+' task'+(todayTasks.length===1?'':'s')+' due today',detail:'Open Tasks to review',go:'tasks'});if(chores.length)items.push({level:'today',icon:'🔁',title:chores.length+' chore'+(chores.length===1?'':'s')+' due today',detail:'Open Tasks to review',go:'tasks'});if(c.payments)(data.payments||[]).forEach(p=>{if(p.paid)return;let d=new Date(today+'T12:00'),last=new Date(d.getFullYear(),d.getMonth()+1,0).getDate(),due=Math.min(+p.day||1,last),day=d.getDate(),diff=due-day;if(diff<0)items.push({level:'urgent',icon:'💵',title:p.name,detail:'Payment overdue'+(p.amount?' · $'+p.amount:''),go:'more'});else if(diff===0)items.push({level:'today',icon:'💵',title:p.name,detail:'Payment due today'+(p.amount?' · $'+p.amount:''),go:'more'});else if(diff<=+c.paymentDays)items.push({level:'soon',icon:'💵',title:p.name,detail:'Payment due in '+diff+' day'+(diff===1?'':'s')+(p.amount?' · $'+p.amount:''),go:'more'})});if(c.school)for(let n=1;n<=+c.schoolDays;n++){let ds=add(today,n),evs=typeof eventsForDate==='function'?eventsForDate(ds):[];evs.forEach(e=>{if(e.schoolCalendar||/^NO SCHOOL - |^HALF DAY - /.test(e.title||''))items.push({level:'soon',icon:/^HALF DAY/.test(e.title||'')?'🕛':'🏫',title:e.title,detail:n===1?'Tomorrow':'In '+n+' days',go:'calendar'})})}if(c.sports){let evs=typeof eventsForDate==='function'?eventsForDate(today):[],nm=nowMinutes();evs.forEach(e=>{if(e.type==='Game'||e.type==='Practice'){let leave=e.leave||e.arrive||'',target=minutes(leave||e.time);if(target!==null){let diff=target-nm;if(diff>=0&&diff<=+c.sportsMinutes)items.push({level:diff<=30?'urgent':'today',icon:e.type==='Game'?'⚾':'🏃',title:e.title,detail:(e.leave?'Leave':'Arrive')+' '+fmtTime(leave||e.time)+(e.location?' · '+e.location:''),go:'sports'})}}})}let rank={urgent:0,today:1,soon:2};return items.sort((a,b)=>rank[a.level]-rank[b.level]).slice(0,8)};
function card(){let items=familyAttention();if(!items.length)return '';return '<section class="card full attention-card"><div class="card-head"><div><div class="eyebrow">ATTENTION</div><h2>Needs your attention</h2><div class="meta">'+items.length+' reminder'+(items.length===1?'':'s')+' to keep on your radar</div></div></div><div class="attention-list">'+items.map(x=>'<button type="button" class="attention-item '+x.level+'" data-attention-go="'+x.go+'"><span class="attention-emoji">'+x.icon+'</span><span><b>'+esc(x.title)+'</b><small>'+esc(x.detail)+'</small></span><i>›</i></button>').join('')+'</div></section>'}
function inject(){if(!['home','today'].includes(window.view||view))return;let root=document.querySelector('#dashboard');if(!root||root.querySelector('.attention-card'))return;let html=card();if(html)root.insertAdjacentHTML('afterbegin',html)}
function controls(){let c=cfg();return '<section class="card full reminder-settings-card"><div class="card-head"><div><div class="eyebrow">REMINDERS</div><h2>Attention & reminder timing</h2><div class="meta">Choose what Family Hub surfaces and how early.</div></div></div><div class="reminder-toggle-grid">'+[['tasks','✅','Tasks'],['chores','🔁','Recurring chores'],['payments','💵','Payments'],['school','🏫','School days'],['sports','⚾','Sports']].map(x=>'<label class="reminder-toggle"><span>'+x[1]+' '+x[2]+'</span><input type="checkbox" data-reminder-toggle="'+x[0]+'" '+(c[x[0]]?'checked':'')+'></label>').join('')+'</div><div class="reminder-timing"><label>💵 Payments<select data-reminder-setting="paymentDays">'+[[1,'1 day before'],[2,'2 days before'],[3,'3 days before'],[7,'7 days before']].map(x=>'<option value="'+x[0]+'" '+(+c.paymentDays===x[0]?'selected':'')+'>'+x[1]+'</option>').join('')+'</select></label><label>🏫 School schedule<select data-reminder-setting="schoolDays">'+[[1,'1 day before'],[2,'2 days before'],[3,'3 days before'],[7,'7 days before']].map(x=>'<option value="'+x[0]+'" '+(+c.schoolDays===x[0]?'selected':'')+'>'+x[1]+'</option>').join('')+'</select></label><label>⚾ Sports leave/arrival<select data-reminder-setting="sportsMinutes">'+[[30,'30 minutes before'],[60,'1 hour before'],[120,'2 hours before'],[180,'3 hours before']].map(x=>'<option value="'+x[0]+'" '+(+c.sportsMinutes===x[0]?'selected':'')+'>'+x[1]+'</option>').join('')+'</select></label></div></section>'}
function injectSettings(){if((window.view||view)!=='settings')return;let root=document.querySelector('#dashboard');if(root&&!root.querySelector('.reminder-settings-card'))root.insertAdjacentHTML('beforeend',controls())}
function route(go){if(go==='sports'&&typeof window.openSportsHub==='function')return window.openSportsHub();let b=document.querySelector('[data-view="'+go+'"]');if(b)return b.click();if(go==='more')return document.querySelector('[data-action="more"]')?.click();view=go;render()}
document.addEventListener('click',e=>{let b=e.target.closest?.('[data-attention-go]');if(b)route(b.dataset.attentionGo)});document.addEventListener('change',e=>{let c=cfg();if(e.target.matches('[data-reminder-toggle]')){c[e.target.dataset.reminderToggle]=e.target.checked;save()}if(e.target.matches('[data-reminder-setting]')){c[e.target.dataset.reminderSetting]=+e.target.value;save()}});let old=window.render;if(typeof old==='function'){window.render=function(){let r=old.apply(this,arguments);setTimeout(()=>{inject();injectSettings()},0);return r}}else setInterval(()=>{inject();injectSettings()},500);setTimeout(()=>{inject();injectSettings()},0);
})();
