// Reminders 1.0 — configurable timing v194a
(function(){
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function cfg(){data.settings=data.settings||{};data.settings.reminders=data.settings.reminders||{tasks:true,chores:true,payments:true,school:true,sports:true,paymentDays:1,schoolDays:1,sportsMinutes:120};return data.settings.reminders}
function add(ds,n){let d=new Date(ds+'T12:00');d.setDate(d.getDate()+n);return iso(d)}
function daysBetween(a,b){return Math.round((new Date(b+'T12:00')-new Date(a+'T12:00'))/86400000)}
function fmtTime(t){if(!t)return '';let [h,m]=t.split(':').map(Number),ap=h>=12?'PM':'AM';h=h%12||12;return h+(m?':'+String(m).padStart(2,'0'):'')+' '+ap}
function minutes(t){if(!t)return null;let [h,m]=t.split(':').map(Number);return h*60+(m||0)}
function nowMinutes(){let p=new Intl.DateTimeFormat('en-US',{timeZone:'America/Los_Angeles',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date()),o=Object.fromEntries(p.map(x=>[x.type,x.value]));return (+o.hour%24)*60+(+o.minute||0)}
window.familyAttention=function(){let c=cfg(),today=vegasToday(),items=[];
 if(c.tasks||c.chores)(data.tasks||[]).forEach(t=>{if(t.taskMode==='cycle'){if(c.chores&&typeof taskDueToday==='function'&&taskDueToday(t))items.push({level:'today',icon:'🔁',title:t.name,detail:'Recurring chore due now'+(t.assigned?' · '+t.assigned:''),go:'tasks'});return}if(!c.tasks||t.done)return;if(t.due&&t.due<today)items.push({level:'urgent',icon:'⚠️',title:t.name,detail:'Overdue task'+(t.assigned?' · '+t.assigned:''),go:'tasks'});else if(t.due===today)items.push({level:'today',icon:'✅',title:t.name,detail:'Task due today'+(t.assigned?' · '+t.assigned:''),go:'tasks'})});
 if(c.payments)(data.payments||[]).forEach(p=>{if(p.paid)return;let d=new Date(today+'T12:00'),last=new Date(d.getFullYear(),d.getMonth()+1,0).getDate(),due=Math.min(+p.day||1,last),day=d.getDate(),diff=due-day;if(diff<0)items.push({level:'urgent',icon:'💵',title:p.name,detail:'Payment overdue'+(p.amount?' · $'+p.amount:''),go:'more'});else if(diff===0)items.push({level:'today',icon:'💵',title:p.name,detail:'Payment due today'+(p.amount?' · $'+p.amount:''),go:'more'});else if(diff<=+c.paymentDays)items.push({level:'soon',icon:'💵',title:p.name,detail:'Payment due in '+diff+' day'+(diff===1?'':'s')+(p.amount?' · $'+p.amount:''),go:'more'})});
 if(c.school)for(let n=1;n<=+c.schoolDays;n++){let ds=add(today,n),evs=typeof eventsForDate==='function'?eventsForDate(ds):[];evs.forEach(e=>{if(e.schoolCalendar||/^NO SCHOOL - |^HALF DAY - /.test(e.title||''))items.push({level:'soon',icon:/^HALF DAY/.test(e.title||'')?'🕛':'🏫',title:e.title,detail:n===1?'Tomorrow':'In '+n+' days',go:'calendar'})})}
 if(c.sports){let evs=typeof eventsForDate==='function'?eventsForDate(today):[],nm=nowMinutes();evs.forEach(e=>{if(e.type==='Game'||e.type==='Practice'){let leave=e.leave||e.arrive||'',target=minutes(leave||e.time);if(target!==null){let diff=target-nm;if(diff>=0&&diff<=+c.sportsMinutes)items.push({level:diff<=30?'urgent':'today',icon:e.type==='Game'?'⚾':'🏃',title:e.title,detail:(e.leave?'Leave':'Arrive')+' '+fmtTime(leave||e.time)+(e.location?' · '+e.location:''),go:'sports'})}}})}
 let rank={urgent:0,today:1,soon:2};return items.sort((a,b)=>rank[a.level]-rank[b.level]).slice(0,8)};
function card(){let items=familyAttention();if(!items.length)return '';return '<section class="card full attention-card"><div class="card-head"><div><div class="eyebrow">ATTENTION</div><h2>Needs your attention</h2><div class="meta">'+items.length+' item'+(items.length===1?'':'s')+' to keep on your radar</div></div></div><div class="attention-list">'+items.map(x=>'<button type="button" class="attention-item '+x.level+'" data-attention-go="'+x.go+'"><span class="attention-emoji">'+x.icon+'</span><span><b>'+esc(x.title)+'</b><small>'+esc(x.detail)+'</small></span><i>›</i></button>').join('')+'</div></section>'}
function inject(){if(!['home','today'].includes(window.view||view))return;let root=document.querySelector('#dashboard');if(!root||root.querySelector('.attention-card'))return;let html=card();if(html)root.insertAdjacentHTML('afterbegin',html)}
function settings(){let c=cfg();$('#modalTitle').textContent='Reminder Settings';$('#modalBody').innerHTML='<div class="reminder-settings"><p class="meta">Choose what appears in Needs your attention and how early Family Hub starts showing it.</p><div class="reminder-toggle-grid">'+[['tasks','✅','Tasks'],['chores','🔁','Recurring chores'],['payments','💵','Payments'],['school','🏫','School days'],['sports','⚾','Sports']].map(x=>'<label class="reminder-toggle"><span>'+x[1]+' '+x[2]+'</span><input type="checkbox" data-reminder-toggle="'+x[0]+'" '+(c[x[0]]?'checked':'')+'></label>').join('')+'</div><div class="reminder-timing"><label>💵 Payments<select data-reminder-setting="paymentDays"><option value="1" '+(+c.paymentDays===1?'selected':'')+'>1 day before</option><option value="2" '+(+c.paymentDays===2?'selected':'')+'>2 days before</option><option value="3" '+(+c.paymentDays===3?'selected':'')+'>3 days before</option><option value="7" '+(+c.paymentDays===7?'selected':'')+'>7 days before</option></select></label><label>🏫 School schedule<select data-reminder-setting="schoolDays"><option value="1" '+(+c.schoolDays===1?'selected':'')+'>1 day before</option><option value="2" '+(+c.schoolDays===2?'selected':'')+'>2 days before</option><option value="3" '+(+c.schoolDays===3?'selected':'')+'>3 days before</option><option value="7" '+(+c.schoolDays===7?'selected':'')+'>7 days before</option></select></label><label>⚾ Sports leave/arrival<select data-reminder-setting="sportsMinutes"><option value="30" '+(+c.sportsMinutes===30?'selected':'')+'>30 minutes before</option><option value="60" '+(+c.sportsMinutes===60?'selected':'')+'>1 hour before</option><option value="120" '+(+c.sportsMinutes===120?'selected':'')+'>2 hours before</option><option value="180" '+(+c.sportsMinutes===180?'selected':'')+'>3 hours before</option></select></label></div></div>';$('#modal').showModal()}
function addSettingsEntry(){let modal=document.querySelector('#modal[open]'),grid=modal?.querySelector('.more-grid');if(!grid||modal.querySelector('[data-reminder-settings]'))return;let b=document.createElement('button');b.type='button';b.className='more-destination';b.dataset.reminderSettings='1';b.innerHTML='<span class="more-icon">🔔</span><span><b>Reminders</b><small>Attention timing & alerts</small></span><i>›</i>';grid.appendChild(b)}
function route(go){if(go==='sports'&&typeof window.openSportsHub==='function')return window.openSportsHub();let b=document.querySelector('[data-view="'+go+'"]');if(b)return b.click();if(go==='more')return document.querySelector('[data-action="more"]')?.click();view=go;render()}
document.addEventListener('click',e=>{let b=e.target.closest?.('[data-attention-go]');if(b)route(b.dataset.attentionGo);if(e.target.closest?.('[data-reminder-settings]'))settings();if(e.target.closest?.('[data-action="more"]'))setTimeout(addSettingsEntry,0)});
document.addEventListener('change',e=>{let c=cfg();if(e.target.matches('[data-reminder-toggle]')){c[e.target.dataset.reminderToggle]=e.target.checked;save()}if(e.target.matches('[data-reminder-setting]')){c[e.target.dataset.reminderSetting]=+e.target.value;save()}});
let old=window.render;if(typeof old==='function'){window.render=function(){let r=old.apply(this,arguments);setTimeout(inject,0);return r}}else setInterval(inject,500);setTimeout(inject,0);
})();
