// Sports Hub — isolated module v155a
(function(){
  function ensure(){data.events=data.events||[];data.sportsTeams=data.sportsTeams||[]}
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function fmt(d){return new Date(d+'T12:00').toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'})}
  function sports(){return data.events.filter(e=>['Practice','Game'].includes(e.type)||e.sportEvent)}
  function persist(){if(typeof save==='function')save();else localStorage.setItem('familyHubData',JSON.stringify(data))}
  function open(){
    ensure();let ev=[...sports()].sort((a,b)=>(a.date+(a.time||'')).localeCompare(b.date+(b.time||''))),today=vegasToday(),up=ev.filter(e=>e.date>=today);
    $('#modalTitle').textContent='Sports';$('#modalBody').innerHTML='<div class="sports-page"><div class="sports-top"><button class="mini" data-sports-back>‹ Back</button><button class="primary" data-sport-add>＋ Sports event</button></div><div class="sports-stats"><div><span>Upcoming</span><strong>'+up.length+'</strong></div><div><span>Practices</span><strong>'+up.filter(e=>e.type==='Practice').length+'</strong></div><div><span>Games</span><strong>'+up.filter(e=>e.type==='Game').length+'</strong></div></div><div class="sports-filters"><button class="active" data-sport-filter="All">All</button><button data-sport-filter="Richard">Richard</button><button data-sport-filter="Timothy">Timothy</button></div><div class="sports-list">'+(up.length?up.map(e=>row(e)).join(''):'<p class="muted">No upcoming practices or games.</p>')+'</div></div>';
    $('#modal').showModal();
  }
  function row(e){return '<div class="sport-row" data-sport-person="'+esc(e.person)+'"><span class="sport-dot" style="background:'+personColor(e.person)+'"></span><div class="sport-info"><div class="sport-title"><b>'+esc(e.title)+'</b><span class="pill">'+esc(e.type)+'</span></div><div class="meta">'+fmt(e.date)+' · '+(e.time||'All day')+(e.end?'–'+e.end:'')+(e.leave?' · Leave '+e.leave:'')+'</div><div class="meta">'+esc(e.person)+(e.team?' · '+esc(e.team):'')+(e.opponent?' · '+(e.homeAway==='Away'?'@ ':'vs ')+esc(e.opponent):'')+(e.location?' · '+esc(e.location):'')+'</div></div><div class="item-actions"><button class="mini" data-sport-edit="'+e.id+'">Edit</button></div></div>'}
  function form(id){
    ensure();let e=data.events.find(x=>x.id==id),fresh=!e;if(!e)e={id:Date.now(),title:'',person:'Richard',type:'Practice',date:vegasToday(),time:'17:30',end:'',location:'',leave:'',bring:'',notes:'',sport:'Baseball',team:'',season:'',opponent:'',homeAway:'Home',sportEvent:true,repeat:'None',excludedDates:[]};
    $('#modalTitle').textContent=fresh?'Add sports event':'Edit sports event';
    $('#modalBody').innerHTML='<div class="form-grid"><label class="field">Who<select id="spPerson"><option '+(e.person==='Richard'?'selected':'')+'>Richard</option><option '+(e.person==='Timothy'?'selected':'')+'>Timothy</option><option '+(e.person==='Both'?'selected':'')+'>Both</option></select></label><label class="field">Event type<select id="spType"><option '+(e.type==='Practice'?'selected':'')+'>Practice</option><option '+(e.type==='Game'?'selected':'')+'>Game</option></select></label><label class="field">Sport<input id="spSport" value="'+esc(e.sport||'')+'" placeholder="Baseball, soccer..."></label><label class="field">Team<input id="spTeam" value="'+esc(e.team||'')+'" placeholder="Mariners"></label><label class="field full">Event name<input id="spTitle" value="'+esc(e.title||'')+'" placeholder="Baseball Practice"></label><label class="field">Date<input id="spDate" type="date" value="'+e.date+'"></label><label class="field">Start<input id="spTime" type="time" value="'+(e.time||'')+'"></label><label class="field">End<input id="spEnd" type="time" value="'+(e.end||'')+'"></label><label class="field">Leave by<input id="spLeave" type="time" value="'+(e.leave||'')+'"></label><label class="field">Opponent<input id="spOpponent" value="'+esc(e.opponent||'')+'" placeholder="Dodgers"></label><label class="field">Home / Away<select id="spHomeAway"><option '+(e.homeAway==='Home'?'selected':'')+'>Home</option><option '+(e.homeAway==='Away'?'selected':'')+'>Away</option></select></label><label class="field full">Location<input id="spLocation" value="'+esc(e.location||'')+'" placeholder="Field / complex"></label><label class="field full">What to bring<input id="spBring" value="'+esc(e.bring||'')+'" placeholder="Glove, cleats, water..."></label><label class="field">Season<input id="spSeason" value="'+esc(e.season||'')+'" placeholder="Fall 2026"></label><label class="field">Repeat<select id="spRepeat"><option value="None">Does not repeat</option><option '+(e.repeat==='Weekly'?'selected':'')+'>Weekly</option></select></label><label class="field full">Notes<textarea id="spNotes">'+esc(e.notes||'')+'</textarea></label></div><div class="modal-actions">'+(fresh?'<button class="mini" data-sports-cancel>Cancel</button>':'<button class="danger" data-sport-delete="'+e.id+'">Delete</button>')+'<button class="primary" id="saveSport">Save</button></div>';
    $('#saveSport').onclick=()=>{e.person=$('#spPerson').value;e.type=$('#spType').value;e.sport=$('#spSport').value.trim();e.team=$('#spTeam').value.trim();e.title=$('#spTitle').value.trim()||[e.sport,e.type].filter(Boolean).join(' ');e.date=$('#spDate').value;e.time=$('#spTime').value;e.end=$('#spEnd').value;e.leave=$('#spLeave').value;e.opponent=$('#spOpponent').value.trim();e.homeAway=$('#spHomeAway').value;e.location=$('#spLocation').value.trim();e.bring=$('#spBring').value.trim();e.season=$('#spSeason').value.trim();e.repeat=$('#spRepeat').value;e.notes=$('#spNotes').value.trim();e.sportEvent=true;e.excludedDates=e.excludedDates||[];if(!e.title||!e.date)return alert('Enter an event name and date.');if(fresh)data.events.push(e);persist();open()}
  }
  function inject(){let menu=document.querySelector('.more-menu');if(!menu||menu.querySelector('[data-sports-open]'))return;let plan=[...menu.querySelectorAll('.more-group')].find(g=>g.querySelector('.eyebrow')?.textContent.trim()==='PLAN'),grid=plan?.querySelector('.more-grid');if(!grid)return;let b=document.createElement('button');b.type='button';b.className='more-destination';b.dataset.sportsOpen='1';b.innerHTML='<span class="more-icon">⚾</span><span><b>Sports</b><small>Practices, games & team schedules</small></span><i>›</i>';grid.appendChild(b)}
  document.addEventListener('click',e=>{
    if(e.target.closest?.('[data-action="more"]'))setTimeout(inject,0);
    if(e.target.closest?.('[data-sports-open]'))open();
    if(e.target.closest?.('[data-sports-back],[data-sports-cancel]'))open();
    if(e.target.closest?.('[data-sport-add]'))form();
    let ed=e.target.closest?.('[data-sport-edit]');if(ed)form(+ed.dataset.sportEdit);
    let del=e.target.closest?.('[data-sport-delete]');if(del&&confirm('Delete this sports event?')){data.events=data.events.filter(x=>x.id!=+del.dataset.sportDelete);persist();open()}
    let f=e.target.closest?.('[data-sport-filter]');if(f){document.querySelectorAll('[data-sport-filter]').forEach(x=>x.classList.toggle('active',x===f));document.querySelectorAll('.sport-row').forEach(x=>x.hidden=f.dataset.sportFilter!=='All'&&x.dataset.sportPerson!==f.dataset.sportFilter)}
  });
})();