const C='family-hub-v292f';
const CORE=['./dashboard-model.js?v=292f','./dashboard-settings.js?v=292f','./dashboard-settings.css?v=292f','./hub-time.js?v=287a','./hub-visual.js?v=292a','./hub-visual.css?v=291a','./task-routine-workflow.js?v=284c','./hub-experience.css?v=284c','./money-links.js?v=284c','./hub-experience.js?v=286a','./meal-shopping-workflow.js?v=284c','./calendar-sports-workflow.js?v=284c','./hub-recovery.js?v=284c','./money-import.js?v=284c','./money-workspace.js?v=285a','./money-workspace.css?v=284c','./','./index.html','./manifest.webmanifest?v=185a','./styles.css?v=114b','./navfix.css?v=115a','./search.css?v=117a','./today-mobile.css?v=118a','./nav-mobile.css?v=119a','./wellness.css?v=121a','./tracker-collapse.css?v=122a','./tasks-cleanup.css?v=126a','./today2.css?v=128a','./recurring-tasks.css?v=130a','./wellness-history.css?v=134a','./debt.css?v=148a','./budget2.css?v=281a','./meals-shopping-polish.css?v=149a','./wellness2.css?v=154a','./meds.css?v=154a','./sports.css?v=184a','./mobile-a11y.css?v=183a','./more-icons.css?v=188a','./reminders.css?v=196a','./task-undo.css?v=191a','./dashboard2.css?v=225a','./calendar2.css?v=239a','./calendar-filters.css?v=240a','./calendar-custody.css?v=242a','./calendar-conflicts.css?v=243a','./calendar-smart-summary.css?v=245a','./sync-safety.js?v=284c','./app.js?v=262a','./calendar2.js?v=286a','./calendar-day-focus.js?v=286a','./calendar-week.js?v=286a','./calendar-agenda.js?v=286a','./calendar-filters.js?v=240a','./calendar-custody.js?v=242a','./calendar-conflicts.js?v=243a','./calendar-smart-summary.js?v=245a','./search.js?v=117a','./wellness.js?v=121a','./today2.js?v=289a','./recurring-tasks.js?v=130a','./task-completion-fix.js?v=191a','./wellness-history.js?v=133a','./debt.js?v=284c','./budget2.js?v=284c','./money-tab.js?v=285a','./credit-card-budget.js?v=292a','./budget-accounts.js?v=285a','./monthly-budget.js?v=285a','./budget-transactions.js?v=285a','./meals-shopping-polish.js?v=149a','./wellness2.js?v=154a','./meds.js?v=284c','./sports.js?v=290a','./sports-colors.js?v=229a','./navfix.js?v=115a','./reminders.js?v=201a','./notifications.js?v=196a','./dashboard2.js?v=292a','./dashboard-polish.js?v=285a','./shopping-dashboard-fix.js?v=226a','./shopping-category-lock.js?v=227a','./dashboard-extras.js?v=286a','./dashboard-edit.js?v=292f'];
self.addEventListener('install',event=>{self.skipWaiting();event.waitUntil(caches.open(C).then(cache=>cache.addAll(CORE)))});self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==C).map(key=>caches.delete(key)))).then(()=>self.clients.claim()))});self.addEventListener('notificationclick',event=>{event.notification.close();event.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(cs=>{for(const c of cs){if('focus'in c)return c.focus()}return clients.openWindow('./')}))});self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const req=event.request;if(req.mode==='navigate'){event.respondWith(fetch(req).then(res=>{const copy=res.clone();if(res.headers.get('content-type')?.includes('text/html'))caches.open(C).then(cache=>cache.put('./index.html',copy));return res}).catch(()=>caches.match('./index.html').then(r=>r||caches.match('./'))));return}event.respondWith(caches.match(req).then(cached=>cached||fetch(req).then(res=>{if(res&&res.ok){const copy=res.clone();caches.open(C).then(cache=>cache.put(req,copy))}return res}))) });











